#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This file is part of the PyDAW project, Copyright PyDAW Team

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import os

if not os.getuid() == 0:
    print("Error, this must be run as root.  Use su or sudo")
    exit(1)

os.system("setenforce 0")

global_pydaw_version = "pydaw4"

pydaw_version_file = open("../../%s-version.txt" % (global_pydaw_version,))
pydaw_version = pydaw_version_file.read().strip()
pydaw_version_file.close()

pydaw_rpm_file = None

global_rpm_dir = os.path.abspath("%s/.." % (os.getcwd()))

pydaw_rpm_file = None

for f_rpm_file in os.listdir(global_rpm_dir):
    if f_rpm_file.startswith("pydaw") and \
    f_rpm_file.endswith(".rpm"):
        if pydaw_rpm_file is None or f_rpm_file > pydaw_rpm_file:
            pydaw_rpm_file = f_rpm_file

if pydaw_rpm_file is None:
    print("No PyDAW .rpm files found in %s, please run the following commands before running this script:" % (global_rpm_dir,))
    print("\n\ncd ../../..")
    print("./rpm.py")
    print("cd '%s'" % (os.getcwd()))
    print("./copy_rpms.py")
    exit(1)

rpm_file = open("%s/%s" % (global_rpm_dir, pydaw_rpm_file), "rb")
rpm_base64_str = rpm_file.read()
rpm_file.close()

kickstart_template = \
"#kickstart file for PyDAW-OS-Fedora, generated by %s" % (os.path.abspath(__file__),) + \
"""

%include /usr/share/spin-kickstarts/fedora-live-desktop.ks

%packages

#PyDAW Dependencies
python3-PyQt4
gcc
alsa-lib-devel
liblo-devel
libsndfile-devel
gcc-c++
git
python3-numpy
python3-scipy
fftw-devel
portmidi-devel
libsamplerate-devel
python3-devel

%end

%post --interpreter /usr/bin/python3

#embed the PyDAW rpm file into the kickstart template, to subvert the need
#to setup a Yum respository somewhere on the internet, or worry about DNS

import os

my_rpm_file = open("/tmp/pydaw.rpm", "wb")
my_rpm_file.write(""" + str(rpm_base64_str) + """)
my_rpm_file.close()

os.system("rpm -ivh /tmp/pydaw.rpm")

%end
"""

kickstart_file = open("kickstart.ks", "w")
kickstart_file.write(kickstart_template)
kickstart_file.close()

#TODO:  Maybe use --base-on=live-cd.iso and then run yum update ?
#Or automate a chroot into tmpdir afterwards?

kickstart_command = \
"""livecd-creator --verbose \
--config=./kickstart.ks \
--fslabel=PyDAW-OS-Fedora \
--cache=cache/live """
#--tmpdir=tmpdir """
#--nocleanup """

os.system(kickstart_command)

os.system('mv PyDAW-OS-Fedora.iso PyDAW-OS-Fedora-%s.iso' % (pydaw_version,))

#os.system("setenforce 1")
