#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This file is part of the PyDAW project, Copyright PyDAW Team

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import os
import argparse

if not os.getuid() == 0:
    print("Error, this must be run as root.  Use su or sudo")
    exit(1)


parser = argparse.ArgumentParser()
parser.add_argument("--de", help="Select the desktop environment, choices are:\n"
"--de=gnome|kde|lxde|xfce|mate",  default="xfce")
args = parser.parse_args()

if args.de == "gnome":
    ks_file = "/usr/share/spin-kickstarts/fedora-live-desktop.ks"
    de_label = "Gnome"
elif args.de == "lxde":
    ks_file = "/usr/share/spin-kickstarts/fedora-livecd-lxde.ks"
    de_label = "LXDE"
elif args.de == "xfce":
    ks_file = "/usr/share/spin-kickstarts/fedora-livecd-xfce.ks"
    de_label = "XFCE"
elif args.de == "kde":
    ks_file = "/usr/share/spin-kickstarts/fedora-live-kde.ks"
    de_label = "KDE"
elif args.de == "mate":
    ks_file = "/usr/share/spin-kickstarts/fedora-live-mate-compiz.ks"
    de_label = "Mate"
else:
    print("Invalid --de=%s" % (args.de,))
    parser.print_help()
    exit(1)

os.system("setenforce 0")

global_pydaw_version = "pydaw4"

pydaw_version_file = open("../../%s-version.txt" % (global_pydaw_version,))
pydaw_version = pydaw_version_file.read().strip()
pydaw_version_file.close()

pydaw_rpm_file = None

global_rpm_dir = os.path.abspath("%s/.." % (os.getcwd()))

pydaw_rpm_file = None

for f_rpm_file in os.listdir(global_rpm_dir):
    if f_rpm_file.startswith("pydaw") and \
    f_rpm_file.endswith(".rpm") and \
    pydaw_version in f_rpm_file:
        pydaw_rpm_file = f_rpm_file

if pydaw_rpm_file is None:
    print("No PyDAW .rpm files with current version %s found in %s, \n"
    "please run the following commands before running this script:" % (pydaw_version, global_rpm_dir,))
    print("\n\ncd ../../..")
    print("./rpm.py")
    print("cd '%s'" % (os.getcwd()))
    print("./copy_rpms.py")
    exit(1)

rpm_file = open("%s/%s" % (global_rpm_dir, pydaw_rpm_file), "rb")
rpm_bytes = rpm_file.read()
rpm_file.close()

kickstart_template = \
"#kickstart file for PyDAW-OS-Fedora, generated by %s" % (os.path.abspath(__file__),) + \
"""

%include """ + ks_file + """

%packages

#PyDAW Dependencies
python3-PyQt4
gcc
alsa-lib-devel
liblo-devel
libsndfile-devel
gcc-c++
git
python3-numpy
python3-scipy
fftw-devel
portmidi-devel
libsamplerate-devel
python3-devel

%end

%post --interpreter /usr/bin/python3

#embed the PyDAW rpm file into the kickstart template, to subvert the need
#to setup a Yum respository somewhere on the internet, or worry about DNS

import os

my_rpm_file = open("/tmp/pydaw.rpm", "wb")
my_rpm_file.write(""" + str(rpm_bytes) + """)
my_rpm_file.close()

os.system("rpm -ivh /tmp/pydaw.rpm")

%end
"""

kickstart_file = open("kickstart.ks", "w")
kickstart_file.write(kickstart_template)
kickstart_file.close()

#TODO:  Maybe use --base-on=live-cd.iso and then run yum update ?
#Or automate a chroot into tmpdir afterwards?

kickstart_command = \
"""livecd-creator --verbose \
--config=./kickstart.ks \
--fslabel=PyDAW-OS-Fedora \
--cache=cache/live """
#--tmpdir=tmpdir """
#--nocleanup """

os.system(kickstart_command)

os.system('mv PyDAW-OS-Fedora.iso PyDAW-OS-Fedora-%s-%s.iso' % (de_label, pydaw_version,))

#os.system("setenforce 1")
