#!/usr/bin/env python3

import os, sys

f_prefix_dir = os.path.dirname(__file__)

f_path = f_prefix_dir + "/../lib/pydaw3/pydaw/python/pydaw.py"
f_path = os.path.abspath(f_path)
print(f_path)

os.system('python3 "%s" %s' % (f_path, " ".join(sys.argv[1:])))

