#!/usr/bin/env python2

import os

f_prefix_dir = os.path.dirname(__file__)

f_path = f_prefix_dir + "/../lib/pydaw3/pydaw/python/libpydaw/pydaw_history.py"
f_path = os.path.abspath(f_path)
print(f_path)

os.system(f_path)

