/* -*- c-basic-offset: 4 -*-  vi:set ts=8 sts=4 sw=4: */

/* synth_qt_gui.cpp

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

*/


#include "synth_qt_gui.h"

#include <QApplication>
#include <QPushButton>
#include <QTextStream>
#include <QTimer>
#include <iostream>
#include <unistd.h>

#include <qt4/QtGui/qgroupbox.h>
#include <qt4/QtGui/qlayout.h>
#include <qt4/QtGui/qlabel.h>
#include <qt4/QtGui/qgridlayout.h>
#include <QFormLayout>
#include <qt4/QtGui/qboxlayout.h>
#include <QGroupBox>
#include <qt4/QtGui/qdial.h>
#include <QPixmap>
#include <QFile>
#include <QDir>
#include <QTextStream>
#include <QMessageBox>

#include <stdlib.h>
#include "../../libmodsynth/lib/amp.h"
#include "../../libmodsynth/lib/pitch_core.h"

#include "synth.h"
#include "meta.h"

#ifdef Q_WS_X11
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>
#include <X11/SM/SMlib.h>

static int handle_x11_error(Display *dpy, XErrorEvent *err)
{
    char errstr[256];
    XGetErrorText(dpy, err->error_code, errstr, 256);
    if (err->error_code != BadWindow) {
	std::cerr << "synth_qt_gui: X Error: "
		  << errstr << " " << err->error_code
		  << "\nin major opcode:  " << err->request_code << std::endl;
    }
    return 0;
}
#endif

using std::endl;

lo_server osc_server = 0;

#ifdef LMS_DEBUG_MODE_QT    
    static QTextStream cerr(stderr);
#endif    


SynthGUI::SynthGUI(const char * host, const char * port,
		   QByteArray controlPath, QByteArray midiPath, QByteArray programPath,
		   QByteArray exitingPath, QWidget *w) :
    QFrame(w),
    m_controlPath(controlPath),
    m_midiPath(midiPath),
    m_programPath(programPath),
    m_exitingPath(exitingPath),
    m_suppressHostUpdate(true),
    m_hostRequestedQuit(false),
    m_ready(false)
{
    m_host = lo_address_new(host, port);
    
    /*Set the CSS style that will "cascade" on the other controls.  Other control's styles can be overridden by running their own setStyleSheet method*/
    this->setStyleSheet("QGroupBox {background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #E0E0E0, stop: 1 #FFFFFF); border: 2px solid gray;  border-radius: 10px;  margin-top: 1ex; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top center; padding: 0 3px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFOECE, stop: 1 #FFFFFF); }");
    
    QString f_osc_types [] = {"Saw", "Square", "Triangle", "Sine", "Off"};
    int f_osc_types_count = 5;
    
    QString f_lfo_types [] = {"Off", "Sine", "Triangle"};
    int f_lfo_types_count = 3;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Getting the program list from the presets file" << endl;    
#endif
    
    QString f_programs_list [128];
    
    QString f_preset_path = QDir::homePath() + "/dssi";
    
    QDir* f_dir = new QDir(QDir::homePath());
    
    if(!f_dir->exists(f_preset_path))
        f_dir->mkpath(f_preset_path);
    
    QFile* f_file = new QFile(f_preset_path + "/" + LMS_PLUGIN_NAME + "-presets.tsv");
    
    
    if(!f_file->open(QIODevice::ReadOnly)) 
    {   
        f_file->open(QIODevice::ReadWrite | QIODevice::Text);
                  
        /*
            cerr << "Failed to open preset file:  " << f_preset_path << "/" << LMS_PLUGIN_NAME << "-presets.tsv" << "\n";
        
            for(int i = 0; i < 128; i++) 
            {
                f_programs_list[i] = "empty";
                presets_tab_delimited[i] = "empty";
            }
         */
        
        /*This string is generated by running presets_to_qstring.pl script in the packaging folder on the .tsv file associated with this plugin
         in ~/dssi .  If modifying this plugin by changing the number of parameters to be saved by presets, you should comment this out
         and uncomment the section above it.*/
        
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "No preset file found, writing the default preset string to ~/dssi/<plugin name>-presets.tsv" << endl;    
#endif

        f_file->write("empty\nclassic 5th pad\t68\t95\t-8\t153\t90\t-15\t15\t94\t100\t52\t166\t-19\t36\t1\t0\t0\t0\t0\t0\t7\t0\t0\t-14\t5\t42\t1\t18\t38\t0\t0\t0\t0\t0\t0\n303 acid lead\t21\t26\t-9\t45\t70\t0\t36\t12\t29\t1\t99\t-30\t36\t100\t0\t0\t0\t0\t4\t0\t0\t0\t-8\t1\t1\t1\t18\t1\t0\t0\t0\t0\t0\t0\nhoover\t21\t26\t-9\t45\t124\t-16\t15\t12\t29\t1\t99\t-12\t0\t1\t0\t0\t0\t0\t4\t0\t0\t0\t-8\t4\t42\t1\t18\t32\t-12\t0\t0\t0\t0\t0\nbendy saw\t1\t49\t-3\t16\t124\t-16\t15\t100\t100\t1\t162\t-60\t0\t1\t0\t0\t0\t0\t4\t0\t0\t0\t-16\t1\t42\t54\t36\t1\t0\t0\t0\t0\t0\t0\nsupersaw lead\t3\t49\t-3\t16\t124\t-15\t36\t1\t33\t1\t162\t-12\t0\t1\t0\t0\t0\t-6\t4\t0\t0\t0\t-16\t5\t41\t1\t17\t1\t0\t0\t0\t0\t0\t0\n3rd Plucks\t3\t49\t-20\t195\t90\t-9\t36\t1\t9\t1\t73\t-12\t36\t1\t0\t0\t0\t-6\t0\t5\t0\t0\t-16\t5\t50\t1\t17\t1\t0\t0\t0\t0\t0\t0\nsquare lead\t3\t49\t-12\t60\t124\t-9\t36\t1\t21\t1\t73\t-12\t36\t1\t1\t0\t0\t-6\t4\t0\t0\t0\t-16\t4\t50\t1\t17\t1\t0\t0\t0\t0\t0\t0\ntriangle kick drum\t3\t49\t-12\t60\t124\t-9\t36\t1\t21\t1\t73\t-37\t36\t1\t2\t0\t0\t-6\t4\t0\t0\t0\t-5\t4\t50\t1\t17\t8\t-24\t0\t0\t0\t0\t0\nnoise snare\t3\t16\t-30\t14\t124\t-16\t36\t1\t10\t1\t73\t-3\t0\t1\t4\t0\t0\t-6\t4\t0\t0\t0\t-5\t4\t50\t1\t17\t17\t-24\t0\t0\t0\t0\t0\nelectro open hihat\t16\t23\t-30\t14\t101\t-3\t36\t18\t10\t1\t73\t-3\t36\t100\t4\t0\t0\t-6\t4\t0\t0\t0\t-18\t4\t50\t1\t17\t17\t-24\t0\t0\t0\t0\t0\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty");

        f_file->flush();
        
        f_file->seek(0);         
    }
        
    QTextStream * in = new QTextStream(f_file);

    for(int i = 0; i < 128; i++) 
    {
        if(in->atEnd())
        {                        
            f_programs_list[i] = "empty";
            presets_tab_delimited[i] = "empty";
        }
        else
        {
            QString line = in->readLine();    

            QStringList fields = line.split("\t");    

            f_programs_list[i] = fields.at(0);

            presets_tab_delimited[i] = line;
            
        }

    }

    
    f_file->close();
    
    /*End getting the program list from the presets file*/
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the program change controls" << endl;    
#endif
    
    QVBoxLayout *layout = new QVBoxLayout(this);
    
    QHBoxLayout *layout_row0 = new QHBoxLayout();
    
    layout->addLayout(layout_row0);
        
    QGroupBox * f_gb_program = newGroupBox("Program", this);    
    QHBoxLayout *layout_program = new QHBoxLayout();
    
    QLabel *m_prog_label = new QLabel(this);
    m_prog_label->setText("Program");
    layout_program->addWidget(m_prog_label, -1, Qt::AlignLeft);
    
    
    m_program = get_combobox( f_programs_list, 128, this);
    
    m_program->setEditable(TRUE);
    connect(m_program, SIGNAL(currentIndexChanged(int)), this, SLOT(programChanged(int)));        
    layout_program->addWidget(m_program, -1, Qt::AlignLeft);
        
    m_prog_save = new QPushButton(this);
    m_prog_save->setText("Save");
    connect(m_prog_save, SIGNAL(pressed()), this, SLOT(programSaved()));
    layout_program->addWidget(m_prog_save);
    
    //TODO:  Run a load-default-bank method
    f_gb_program->setLayout(layout_program);
    layout_row0->addWidget(f_gb_program, -1, Qt::AlignLeft);
    
    QLabel * f_logo_label = new QLabel("", this);    
    f_logo_label->setTextFormat(Qt::RichText);
    /*This string is a base64 encoded .png image I created using Gimp for the logo.  To get the base64 encoded string,
     run it through png_to_base64.pl in the packaging folder*/
    
    QString f_logo_text = "<html><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAAAwCAYAAACWqXFuAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wDHRcgB15yh5IAACAASURBVHjatd13nGRllTfw763Q3dW5e2a6J+fAMIkchgEBJYmCIAomzGkN765h3XVRX93grjmsuuqquyKoiKIgQSTngSENDJNz6OkwnXNX1X3/6Fsz1TUdBvTtz6c+1dV96977PM95zvmd3wk3MMpPFsHwr0EY/S0Y8Xb4HYR5fwgL/ln4ufAn9//RzhGOdrFRvjPacS/nfAr+F45xr+PdZzDGWAuPN8bnseZtvLGN926ca411DROMzRjHFxyT+3eYd64wNsb8BKMtQpj3v+iAWN7xQf4xEy3sRMI2npCGY93oMSzwRN99ucIznlCEYwjreIs80fXDlyH0Xsa9H6vCGG9eRpvOvOPCvL+Fuc9BJJDZPGE66r6zR/4YFAhcEH0vCCOhy//usSyeYx/MKz7eX+l64RhCNJFG8/9hvOHLOP8rud5fcv8F/88JYU7owpBs3ucRgnqUKc1JZvaIVgsiDRdDLIwEMMgTymPdpV7h7jwWEx28AiH6S4UlHMcsHyu8eCVQIXwZmvUvsUCjWZJgAqsUDmu4MPceiVQ2+pwdzTQfpcUKtV5ILBLAeE4IgzzhCyZYs/Bl7MZgAnM60UL7C7XlX0vrvtJzvBwoMBF+HQ+7Ba9gYx3DOfLRWxgJXjY4IoS538McHsz9JAoGn8N3hzVfTvjyhDDI04RHyVGYpyWDI+caVxiDIzjh8E4KxtgxxyrAr3QBj0UbTSQsr0Qgx7v/gnsKCqDR4fnNM4Gihc83iROZ6yAYff2O0nJGvgqHnjVSSeXuIfc5Hy8OC2DeAMIg0nI5IYy0Xjw8IoiHha9gkWLRdxMhRcHwuXMadDwzmo8dsgHpaMekkQmjXTSaIIYTmNjwGLVkMM5x413zWCFH8FfQrnnCF4/WrSgkkVMUubmMtEwmYChkCJloHo8yfXn3nVMwSSRz583D+7lzZ6NzDonWJzgi6DmMFwQFCqpAcIMwb2kSo2iww45ImIf/8m4o3xHJH08CRZmYynhWJVIozV/X4IgzkylYxNzNpfuKpeNZ/ckhvehDXySU6XzPKhiHaijUZi/3J/j/bJ5fjvDmHZOzSMWZmIp4VmVAWTTv8TzFkA6ieQsDnUJdAYPBETxWKNCxSFmk+hMqS9JKDZ+3KE+IcjhuAP2DSV1FQzpD+qN1yQnZYdYkHPm9fI09Qm8lCuc9D+PlBjSqA1KwULFo51TFs6a9+39csGedhZPKHRzoVD24U3W2RjI5U1e83uBATHXmVilDwuQCXcVL9NTW6a7eLrzwKbsWbdM1f5cD6MwG2oNQe0BPyFBuQKNM5suiHV4O7TIRpzYejTLehjgW/s1IeBRPU57Mqn3T572ta6fSoSpzk/QHx8kUzdI+NCDZ1SF12W6PfPpfPBZdo8Pw3BVahZwApjC5JG3Wpf/iKlOlk2XCzDPK0geVJvp1DWRUpQely8+149br3G5oWGFE1ilTAMmCyNTm/IhsOBKSZUd1QsIjGioeRKo+jHZYtAPzecDD8xSZ3bKAaT/4jNP/5iPeZ60pltnpQUWazJHBu71kj3nuUuppKZ043aBvWe836m02yZscsFhb7SHZL3/W2g/82HP9xfaXDGhCZzi8C7OvRCGNQ9aGYcGmCicw0cdynb/CfeWbtVhIScCkf13h8uuW+KyzZbzBFgdN9wOV/sUBz6lxqSH7BOFsfyu0OaQR/QXeaG6tS0ImBcw45QmfeXqFRQ4KParEHdISAj06HGeSRkOmiZ9b7Q/3f9p30RpZqcwopjabZ/7TEaQ67JDkxhobzfTkOyRjkK1BnirMAdZiVN7dY6XvmWGltAq1PuRTlmi2TKM7LPSouCX6nKrLVTqcZL9/VC+tV4O0F9RhSesktR/8kan1e7wrnrEUU0MqgmGckrtmzmHJqftCB2ZcCQ1GwoMRnlz+OfNBd975R71WMLpXOOLeCu5zxPWMHS3IOYbFM6plfFCvh8Tcao4uey3RrFHapdp9ULkHlf38bZahNCAZFKx1pJ0S4fD/J+9YYsXTp+tSqluIJj22KDdLm4xAi6zVsmp0zPmVdGT28wcaFjqjhQYkHCXalii8qWB0q1PoeOR7MjlgXISKLfPV+Y4SSx2UlnCp1a72sB94rTX2WWmf35spLiUQ123AcYqtsccM7Wbrl1UigxYnNM1SVtpr6VCRIfRHOCSd23VGYtYgWsx8uBAWUEcKBMwoHp38741ikoM8zitfeI8yQUZ6ruEoJj8cbVMEeccXaJbYu57R+u5fS5mr30KhclX+wa9wpv9jlit0WyZ7/2aLr+WByLkoXOdY5MhUou6CH7nYLiktBhRJ+6TnrXCcOrvtUuUuU202WD7fof952j3ZQDYIj2jU4IhQHx5TDmeOR9clTADmC+HJGGeKRZ5v2Y4yRT5mn2s02mPAVOv90QLPafCweY43YI2Y/2unbt0q7LTNZHdbZb6ElB5pLYp1u91s7zGQToq946uWXv9pDSEdEcjOhiPh3wjiPA8Ix/I0dj52zPFSOVORT6DmPMMgj56IBSNlJ9/UjKAlcmxCAZ+a2yD51NOIqEG+4I/Ft4Wkgx69Re+xa/AJM3Xbaqo+fbLW2uCDFvmqUlcZ3DDfVMOWKeHI/eQrjdKAmjvPt3zHOeo8YJoHxXXoN9M0ZfrUOegCdZZp1i7znW+5H12xUG/OMZwIDo0XA05MRDEYJTFhlOSEeECJuJL+CpNtUeenOrzdemmlXu2nTvZPuh30pAqrNLjZFJsdp9xxkmqco8NS2/GQhLhB8xRL+ooyH3L2Lz7s+us/bVpAU0hnMIwrcrxk3LCZSUaaOGmYSkhEYwwKFiAbadG0YQ9xINKsQxFmEZ07GVAcHr2AYeRtDmHQEbojZ4pyODoZbcwctTFiQ0eYbCjv2um8c+Q7e4c5tuia/TNDzTtOkFKs1AlavWiRRqc44CUHnOh+xY3TVUcebbJgA8VQnI6pSmRNv/Y2pwY/Vh8+rdjJOl2uSYesu8w0pN5taj1raP61nnz3jV7IBlqD8DD2C8eCcaNZj4J8g6NomJdNU4RH3PjiW04z2UL7DCp1ilYVUjZYY5nve1SL7eb6oJ/pdZlTFZunxy3mm63N3eo1OuhuH3eBJ13gHleZosd0rZZa4ND3/sbSj3zflhzHGGmanANUgfKI/qnITXxvsdKgWtCfkAj7BfFQNt0qiJOujmkLsjrRFdJrWLB7IyEsDobPV5x37nS0eDmB6Q7pCY44R+m8yFHJUFxlMqM00jSpPFI/50EOogv9YaAzCIevnYM4RpqyXGx1CAPH77FxxwVmmqTI1yy2QpMt4rZa6S6P+YE1jX8yHWXRJsiP5SdRlsia9PW/c1LLDqvMlfSQrPVS4g7ZbpGzdLpdpesMeErPzR/2FBpjoY4wonYK9dd42i4cxcImTJClcQzEaBBpnNRdV5tip1KXane/YrU2maMIldZo9BpzdfmQwL0aJNQq9q8O2CKlzSTPqBcodp+VluqVVeRJNa5yAIPV7Q5EXls8unA8Er46zLzx4xbeWmv5xvP1NE3V2Vrm1YPTDfml+YolXOklB82T8px+5aU/V1udMnDJVlv++zv+jD3pmI5EVh9Sf1pg5buv9DepHgNlr7Opd52VyRUODu433VX2nXafF375Vven48JERiaCBQGKsjFVyYz6N97oiqeSVhfP0mOTZLxdb1hGplZVGOjXZeD2L/rP43bYZJg8zuYwZEH0IIzojKGA3pPW6v/jNXp8xgzHa9es1nzPO90y/+5ELzo0sMZUd6gI0oqiOctBglQmpiaRNesf3+m04B5VYcKASXodMGRIi9nm2a/DmWp9XOpVqz154kEbQw6hJ6f9wpEc7zEHCcYioifkwcLRCdIkSp7qtUi5RjvNVWuvKpP9wmSXG1Dvd54Rd7w5N7/DlPN+b1vDEul9PWZf/Z+Snc8LwxO0WO6QpZ6WljRZryslHTTXVFPfdqN1kTbJ4aqigKqWSnOmtPhbv3S8a90Z6xWETS4Lp9vi9xbo0upkTXYqcZtWlVb5g5ref9Hav0zHTxqd8pNvO/HNf+fFX3/LjZmY7nhW8hPfcFFDk/lBmd0GXSKUstNMaYngN2bs+KiFH/uWhqWb9VZ36M3TgKXxrMk3vNU5v3uLy4MBoVb11iuzR79Z+i2QsltJuE7s2k95y5N/458j2DA4DncZRnTG0NVr7f7SLXrFFdkj0K3amxVrdcBK8+1X592euvU36i57SlFO+0barzyRNentn3P+0DZT3Cbr/dq1GzDXDmUmu0mZc5V4VLHJeh74V/egKdL2Q3nE9mjQbMyIUKEpThwrMTqGKQ7yHZBdS2RNtlq3rXYrt8tsJ9kuZsi99gud5hYu/oNtpWlbKjcaWpJ16KZ/t/Kiz5vtUSusdMgsKXM8KtAoa5XJluEEPO2IecoJftU9l5gi1OFanxSqzpY6S79nrVfpoA5LxX3PbHM1mKbZViW+5JBfqc9WSelR7d2Cm74ptf1qFevOdCNitW0qLNAWhqYalLZAvyJZsw2EHWIOmvTr1U759pM2GcaKA2Gk/eJZ9Z/+qouQDYt1mibuvQKBds2K3GNAncAFSk5tszvCrmHBOoSjOCGZgP7jH9fvDJM9IPAenYo1263RH51qmT7TpfSZ0XiWJk8pzYXZkOooN7mq19wbLnRqcFAQftZWg5Je0meVMg+psFq/0CSvErznMY8avsd83i8MjkFpTZQ3GXs5uWIFTkrO/MYjDjDVdsCJ/k61h9V6XI1BxU6xSbNzrHSSHq1l7YKyIc3oTGT1Juh/bIEip3rEW61zhafElQpcivfJeoOYKlz//EpzIqchG12/COUPnWOKIrfKKLbdbEOazdFsigZTxdRqN98Wi7V6CaFe31NtljY9kt5kjwP6/UTN0zud/a1POxc1V2+00wnKpAw5hLk6TdflVC2KJaR0PXKWORHuLA6G76c0nlX9ww96VcN0i92qQo8U1grcIPCkOv3ON9lrBeWnafjeuz2RiQ2bcCM5v1ieV5+b+0yEHbur7tZjqqzZSmxTaYNp1mhxgn6X2OOQ7I+neaMjc1UcUlXVbdIZT3id9crCOyTt1OdF7V4t0K9CuQVCKdtVJc+09Sc/dRdaQroj7Jvz3IMxEhMmDD+OKoDBBDHUMRj+BIrvPMdU5QZ83qBL7XeeXjUadDrJQxapkXG+3uPmazdMKE/GzEPM/+IXbYyts8gfnO4Gi5H0IwP6bMa9YrJ4z5zdUobjj5k87Dlp30xPykrp8R4Jp7vTIv9mjefME0hbrNgbZQ2a65MydpphqS73qjJFxsMS/lHMDAPWyf7bdY5H2ZqbBH4kab+UK3GWHVZp1iZryGDsVhVbXw+qMoGSkFR2eLNM/fwXrUKzWoNu1uM3ThVYZa8V9io1VSdab/yg36EnnjUY8WjxPO/98CvMSxKIhLBv1m49PqDVjercYbpSFWZp84JBs8R1yLRcpT9yylIoHywy+aXVFq1tMdsV+p0rJibtFHP0KjNdsbslnaDP923++nXW4iDa0JeXZDqu2ITGz1APxjPBxxLID0cGsot+NWiFs7X7pVr1yr3fH20RqjDFVbZqdbUaj0560VX3LLdk8wrTG06w8V8/aY47nZQt12CTIZ+21npJiySlwH4vWXxhpx9Ud1gYDicnZKLrJwOKbrvM/QZdrdL3VDpZtdeqN+Sn5jlbh+9IeFqFT9pug1m+YJcG5abrUm/INh2WqTBbn+kqm5PC3gplJ+zU5FWabFbjST2GVNhhoZP0OV13WCHV1WlJ62S1pV3KSwaE8azaH7/PyU31prjeLGc5YBqS+q0z1SZV1ipXJ3tcvYHX32ZbhKmKAirCI/ykMUxcLBp35rh59r/YJXSremdptkiflINWq7bRYjMNNE5RHglgeSamrHhQ/YU/dGlQrij8mWoLtRlQ5UlZ79TvKXHXGnKJO6bf4ZSP3eKJkBbD3n46L8k0eCUJHeN6wUxcxFJwXCwXAdnzFXt91Gu9xWZX6dJiu7gT3W+S+arF1Uq68e5PaL77w6YrtVmnN/i1akXi+hT5iV96Wspu1V7jAB6RNcnxvvHVFU7A3hxNEgH2oKtcLy5TZKob/btXaTPDFqc7pF5s4XPmVaeVeqPGZ75gbvYq231TndMNOl+3UK9zNDvNkOkme6eNtjnlkTM8e+Gf7Vv9or2PPajOGhX2GbJMr+t1+YJM+CWzfN7uTQvVrXxBZWZIUTyr7jNfcJasSm/TZsCQlFb3mq5BVqDM+w2p1P/AMndHc1kREcb5Yb5EnknOyWMmomESKDrtf3Xf/A7tzjOgTLsK7ZbJuF+5ZVqkTOmNqUMVasKs4tvPtXD/HPW+arLL7dMplHBIqNFGpSab6u89KjT/5q+4Hc1odyQG/4oTdMPxvODwGALuwdGZ0zmytmzTVHN92606JbV4UGC6pyz2iJX+07MeN80sSz1khm0qvFeZpAe81Xz7NJlpqVtMs9JaZU5Rab/1fmal36152MKVL9oVcig4AoITCHvKFEXm5Veu0XTF1xz/8XuUnLDWknivTHe1vt7JOvsPKZlX5unv3mHyP9xso89a43699kmYo9QV9qu2DUtl7e4vN4iBSzZoemyRwPeUW6jYIi/6vEP2WOmdOlF0x3nmrX7CVqS/+QmvaptpEgZ1aVch7S41TjBknphKWS9KvHmtXfW92r58uTMfOtvU1CIDxf16soMSAxVqZu2xrrPSlDAp6ClRV97lQCYpaK1R9YZbPPWBH+u7skHT3x90gpkG1dljsoxbLLPCkEZ1FhqU1vnQalPPeUxPgtRVX3GllH0uUORpKado9IJB9VgmNFkfOl99h/4zH7QhpCWgNzxCOod5Ic5jUnzj0XsJ49jpcGzVeTgCEu3c0oMPOE6Vdo32S3m/K3zcbBdZY5dunebabY8i57hFuRX22a9KhQ7N6u13i7ku1KvVlRZ4xI3+yWXuPf9uv7/3IvOygb1BeJgCCCJcVDS1UWb7XDP/eK6zUlnBAymdV3/OS01nexgXYYUvmm6pDn8wxeWaPGySqba4RkapPqVatNnvu670PkN+pTjsBz2vfsy+z92gxRrlHpVwjZTbLHCutKxi+ww+cJZ61CP2hWudFvxOMjxHt8m6dJpkriLlepVIqNbtZMGvz7N2/3SVn/29Mw2YJi3QKm2WXmw1zG0u8CczzTPVAs06VCvRd+clWt52g90LXtJjqhKX6RE3yS4zvMpLBqUk7RZT6hbT7j7LonMe0/+jD6noP1XWDeZ4i5f82YnKTXIqGDBZm12mma/iD6/3BJoDOh0hnUcgg2NNRxpPA8ZMwOGMBh7DI4HneEDx/dNMt0DWawyYarHj3Od7vmyZW5ygU9YOA5401aDAg9isW7GfmyyJ9aabb64y+8yy181Wxd/qnz/2M7F7L3JSyL4g1BIM478wEvrKyJGZctuFwv/zP+76wGe9cOMP/bjpbHt92A88YLlPmewa22V1eJODQuVqVWk2zwZZT0vb7XZNZlttn1YJH9E+d5MOdJ/5pAOaldgp7XP2C/R5vc0m6VSuz0Nqn11jJmZ+42+c07VKeXiGmMkGDGjyJ73uEXeTpA1qEX71ix5H162XmYEKgV6lNplln17PYA+a3W+uSpMUa9Yj1KzRM8r1eE1HlTKEc3d6Xtxv9Cg3x3Y1ytVrMUenAUVWKFp7yDTM++A3natdk3Jl/tly/+RWdZrcbLql9tmiTp3+f3mbx8pCu0Naw2HHI/MyM8wmVIvhWCY4GCPBszDxMzxCapb88Tx1Am2eN0OPTQ6Y4/O+r0eJmda63+W6dDvgYu/TIaHKE6b5iAN6NJghpd7TupT7totcZ0esX+V3Pm5TNtAUC7VF7Hs6imtWBkxvT5hds0HMYltwroQVPutis+z3DXd52CRfc58HnWiKavS6X48ie/2jFg9a7lz3eczb1CoyoMQhg8p0rNqp0TDtEKzY45kXljrF9832fhuFpqFNSpu3WtLLdiy+7mvKYx2C7C4p16uxQtbF2rxoskBaiaG6uwx86uvWIXzodHWoELdDIC10j1Jxw1kmKefZq0/GdnFxB2y0RFogpnd6wzAWnrPB5F0xs5SoUSaG/8JBnV4nYVWwX6rrYtm/TThFibSMci16zdDvCbMt9JgTHW+tJabpTmRt+qcbtUQ5hF1Ran+Yl5f4sk3weFY19golOZdik0TqyTcq94w5ZlgrpkaNg/Y4TcLzfu0DmsVcabbpalQ7YI4u0yzwLhd62EmmqhV4zPUWuM463DZUouGqrzsuFh4p7wuHQ2+lAVNeXGpFzZD56lxhl495Upci251rswvs1atchS3e4+1e0C2w2xwd3iqj3RxZ5Yrc6m7TLfGAx8Sc4pA+yckx/VGctxs9V2+wWbkBH9QiKS006Dn1utXYpdUOk/75S4b6Up7IVjlokm5LkValxywzJDyiTie/fYc/RpTG4LqV+vQ7aLOpmu0Q2BdtsrkyztWqTcwuyz0u1OYNDigTW7ZeZ7Q5upY8o9Mc21Rr02G/Hc5zwKV2Odv9hK/z+PpXa/n2D+2VUa5MzCkGnGmfaYqEVkppcJxD2jT8x3X6sS9HuxiZxKrABOdXUAYT1eMYjwcMjrEmIq9rQjwc9oBreue71yc9aKPTvcNe+52mRIlnXeMyt9lltoTbxXQ65ATVnvVT1S5Q5DU6tSh1l/Odp0KD27HFVlf+9hNuaa00LSQVJVUWRZTC9Nf8yGL7LBG3V43brHLAbB2O0+JWy3zPdHda42P2WOEUCyyyxwqbLZUx1S7rzXempZo94EJn6dGo1EleXPmUnYa97Z5soPukhw1Yql0cQzIO6DfZkHJp09Qql/j8J9QEPcoMWWSbXotsdJmtquxTqcuntJy+1641LdaHwynymW0nmSwrYYm7TLEds/zZcrss9IyULjMVK0K9Tov0KHOJ+y98zIbIInS/aoNdDjhTxiH9Dtktabd6++3wtA6PW9L3gPlaLLPXQTxplV9K2mGx53WZa79LVft5fbG5n/iuh8PhkFt3LuU+GCMgFowD34JjVGaJsYLHxihLzEtMzTkgyWdWutAtznGFB/Fn7/Jf+pxildn2KHKFF+PXueSJx/zpuXtVh4HeD3zDWl0WGDLkIa91pW86ZLdJ7vWo71iswY0+8sf3uf3ab6gMaQ+GaYiae85X2bjGd/T4kZRvC9X5tTXO1aDLLKsNCtRKi4spcbvAVjO8yiFv0iXhkFLv8t/6haZYo1GVCrNs9axlxz9pT7TAfUEodskD9klqlhbImKZG6Dmd7lTrJL2eVed99oehuQJ7zdDrcTFtysxWZ6YdqH3iXX5l2JMffOYk07BCnxelTVdqrl+Z4q2SYrrNxgH9OtQo1adBkYUqZM067SnPRHmR2Tf/1t63/doL2CDjbP1q7LRTm2pFBmXt9gsLPCxttXJzoijHYgM6LDbLFtW69froY1e6OTMMeTryaZeXU+56LEkIo8aCg2OoUy0wwXGUdJYq0iL0BrfZZqmFVljvXDHbLZIy2w+kfO68Q35/yn+oPeVhTTh72wI7v/IZGzQ435VuknGTSabb5pvOEvNdJ/uYtb/dYN+1TIlCQdmAmh++WxYrrZd2phkedqI3uscWp1pho4+4Rrmeqst1nn+DttO2aJ3VpuqhR0z90ZW2uM5FjtNsuT1aNTtNoFup37nElbZc9Hn7I/PTH224Q7P3ye4p0qbOIR2alVtplg4nSWlR4iXTPC/mLXY5QYmDZlqOtIRWqY9+z3ppuyNaI5y3QwO+YZKFWKrNNCeoENMlKykubZasPlkZGWd6QYtBM0w77x47A9pCYomM3uSAZ4eKTTagziw7zbBBt4wOk3SYIaneUzhOm92y5nrSBm+x1RylMqbZ+apWW+ZvciC6v55cWlh+dnZQwKiMIjNBeKyAcIyipFheLXCuICkRpT3l4pGxiAKpCpj3tfc679NfsVTMw6rdp8s1unC7C12sWY8Oex33llaP3niNR9GUjitNZMwKup2jzHSh/8YBG1xjuT1esMIKjVrdrNYZYaANG6M45Oyy7/p47/vdYZ03mGmbNru0KPEa7a73Zq+x98RnNT1zqTT2R3TRrBkPK24IrQ6n2KtfxizbPK7SkJm2KFGtxhkawxP8GM+FNAaUYP6Hvu+qH37YEo+r1KDPpdY5oNhcceucpktCk8A1btFnjV1KPKTMJKXFF9naX+l/QzYFNEdgvvb5lRbed776KS001JuRrlAUDgrSCcnkoIHBpFT9fvuHiiU7upQGix169w9smd5gb5SUW4zFy5/wug1xCw1IWWDncPKaHtMU+4GTvUPC7/WZb8BrrRVX44Aq++0x3QrzbO+c4oniPs8VDQ2fO8rsyY5Gt0zQUCnXoiObV+edK0rKxbuzuazdxMtJxSrAjkmU3HWGGTaapMgncY7J7jRP3CL3aVRuiSccp/l1b7M/yqZoSmSUYMob/+R3v73SZjGPGfRDy633B6uco8GQO2zxPmc4+MfXir/uDhWRVirv/aj7DTjZDk1SZnpRkwvt9hnH+YRN/mzJ3N+rxIsRSV19xc/tOlDrfH9ySIeZptlhsc1WW+JBBKZpFZTX6Yyq7/qjqEMwlND32tvs++GHHa/VFPNsEuoRmuQzVtuuRIlWH7Zep3tVmqzIHKeqdZKm66/2EBoMa62eaPEyq9brW7XejgjKPDvGGsfzKswGoznITwroXbxZesMVetyr32MWatZjin7n2OUkgWKDFmvwJk8ZcEiRWeZqsM/Vih362D9prOi0C4dCeoMj5Q4jOlMcixccHGM564Qp+RNozVgu82NzhYXB6XaGj0oJpfU53jwP2ulSS3WocAm+fv49zsllEEfE5v7/fYfy316pVtYXBW6X0epyj2O/Tt+UtgI//a+pTnvdMNUxfIu7zFSvwjt8B290khtt8C5f0u2LzrJV9S1bVS/5gKI5b/HC7tfwOQAADQVJREFUn8+12UOu9At1TtbiHA97WI0GJZ4zaIcpFuhziZ7jfm0gWuTBKDN6KJ7Rc+F9DnhBpTRazbZV2ku6lTvgnw1ZJ21QTLvLBWarVSvQsvoJv3jTTZrD4ZBWdyTUYTAsUP1oz6s/GbMXS15CajoqRwiiNLjepY8avKVIvdNsV6bfdL12a7Bdt15bNUhartvj6i22TI1N4uY53574gO3f+Zpn03FN8YyuSLDzEw4KNeC4RHQ4AY88bkr+eMmnBROTq4KrbHyd7rDTdJUO2G6aPaps0ut0j5trtXstTyxw7tQm7VEiwSAy6biOeMYclAnsMOBrit2AP2vwTuU2W+MJWTV3fNMOPzU5AsahA6ql1EoIvKTOCueZ4QmdpviErZ5xkrWKtuw2a8t9+n3Bax3CNbo1iUlqM0m/R8y3XLPl1lqi1l3mndxlb04AIwJWLNRXMqC5dptDrS2qbEKbemUCJ3hKmRL9TnSKJnvMN9seoSpV/PB8pdgfDHu+gwUhrXRwBNYclUEyyqKGeen6sVxNyiVb7fy3bzvDI3rda7Fd+lyg1SL7rHS7lEE7VNrmVHv0OcVrLdCMvhuvsR6HEhltUaZRNi/n8qjmVWO9B8dWvjF2JGSshK7gaA84V/NQPBhXPFTmtypsMc9mZzsgLiO0xAI1bhKK6z17rb6I1BwIhzHBYCKjp2RA/8V32IK1ir0Nv5E2X0attGptzhYzL6xk/8zDvGN6ecoGHVJi5pqhRZNZsuY5YJ5nJC3X5AytPu4B5eZ7s33eYb/nJHWp8u8u9WsLTUadpMBkj5rjLJ2rnx1emOAIBkpHgj/w5maPer9npCT1qEa1jZaj3UWe9agqMfOEqgVq3nCbF5fvtiGMTFteFZlIA2bDSKs5otnSeQVTI/4WRr1ygiPdpjIYWHO/ViXanKfSKoPeJ3S8YgfNs1edn7oAU73GFmeotsAu7Xqnrrfzzb+3JxM7TLqn80NuwSi5VqM1jgwmyHoZL4QSz/3yf0cSzEFBMmR+ieLhCv2fvd1xt52qXtqgSe7SZY8T7bXaQXsl1cs63Z/PfUb9G35ve5RZ0Rup93hIau4u0372XgsMeAxnStgv4RGB/ao0+gcXW6Ik1ia4cO0wvC7tlvzD+z0jNFO5m5RbJCMtba4Wg2J6zPWin1lmnlaNqlyrzyo91ogZMqDXfFvUOVXMR610jVb1tl//di8UDdkbZYAMRmNODsZVDuy38OYTnWObCtfY4XS7LdYkoVZMiU0mW64PL0qav3GpX2Vi9sTCw0KdzSukDwq6gh0Th1aAx+LRWtR8620WDARSTvOwOcrN1GyqOaqkJEwXKvddZ2sx0+NmONcju5d7OtlvTyKrMb/OIw/LhQWRsfxuGOFoHbYK+/3kNkt+s8rcuL84Vix4PNWZV7yeuWG/k33BR9zrEgNe70GXmqRXpy6LPGKZl/Cbv/269Ya1Xy6onQkZCANtq56XEvhB0QtSEgbsc4FdvqzP8djm791klod/96bhCQrpetcNGsp3WCNuFY7HbEX+0VyPudhNVnnAzV4vY5IbLNeg1jfM9Yg6Dym2ValPeNTXHDDFoDs9p9Pc2AELy3u05Jmiw1MRD2XO2e+QpXZ6s5e8pM8eKVXSdmpWKrBCXIkSKSd96R/cgcZYdti0BSNNm9HMXF6epXCCdsqRJGRzlXULthvCPNTptMGQ7SYLJEwzzV5JJ7tG1nTdPmbL6of117boSmS1OlIJeNj5CCfI43sl8eDw5dQFG7s+JGet+/auViLQ6jG1bnOx15npA65yri3O9gez7MX/mbfLc4aJ0yFHqr6GhLorejSWveRHg5P8UaezJG1XI+sFr7PGAo9ZabupO97uj5EWacsGBrsW+F1Vu5M7qwzodIpyPxIT06hYkcU+7kXPKvcuHTZLJkLd6bvM0iNmv6x1VmiXdZFiWb+3SuXCzfZFmm8o1wYjyssrCUIlUw8qLsp4YLDJWQJxgZgBCd1WqtBtnTkydlTOtelzX/FcpPG7omq3XDuOiTrEjRdQCPKFN69jVefyRpufuc7F3uhkZwoUe9xGk4Q2q1NqqmekTAkGtIVx+3/9Frt7U/al+rRHuDyb381hgtqicVOvxqor+ovrgvOa5QwFDPzdd/3pU5dZotxg8FFh8Jx14SIV6gwGWccP/sKbz4p7uLLTvnBkh6Zs9HsXWh94jwcvuFNdyUaP95Q6N2xUFjbo9T/qddg7+HqP/92PNRjOzG2PhTqHEoY6qoWblmhdtcGXB2OWGHDIFCfabLpDqiUNLt/mmd99ycaSJmVLnzXX9Sb5tsbwYYvC46UESsJuF4cbJb/4BQ9FWCgWJTwkUJIN1MRCU7/8BssG3+s8H7ffHiUm2WarhE1SMipcpVmPF19aZV020BiEWiNPNxOMAonyevCEwTH0KgqODjRkI7qo9VPftuGOb7mzO6k8frfGsNPi2EWeyNzn/NgFng/3qYhVWRt2avv7H2ufud8Gw0X+ffKwaUEXjMJeNcFE+YDhOEGN8YrfcvYmltcTOkdCJ/JrSnNVcCHlsZhqWaWG+4uU5PUgyZmvdvSk4zoSGR1htBiOtK4ojgq+J6M6es/dX671V64h4qFsoDUW6omOKc0M11/Ux7OqWyYpGioRHqxT3l6qdFqXvhkb9FVkdAzFDSUzh9tg57onpPMwT1q0QbKBdCwUj7KIq6LYc83PPmTZe35gsX8zzxyBWwxql3KxbWoUe43QVI+c/Eupde/2EF6KMkr6gjxslec1jujINVaJ4ziUTK7IPFeYXxPdb6XhvozZaKwD0XvOoepDRzicbNAZ5K3JKPd2zB3I8r+TV0Q/ojtWmEdEK2g1kZ9kkPNyc8UwcUfateVqEmJRu4liwyA4mSek+U51zoPsz1EQwdHtwZKRIJbktZDINzVhrh1F9Ern1SMXIxWSysSlkMjExbOBMBZKxzIGkxkD4RHuLR6NLRhFk2SjcVXdcK2TPvAB74z1qhAa6k4p9aSq4ALN4TzVtjjoeRVO1Og+syzBk2LOt2/95W5f0uORZMaeKJlzKK+5UH7XscKWcKGXJ4D5TYYSeWtRlDdGBUIVRuZ2MGQgR4nl16DkFcIHo5jkifJOR7QRkSeAeRs+55QcHQkp5JwKNWceE56r0M9EgD3fezZKNX+moB1ZkNccKIx2R19enXE+0MjtppyQ5BYyk6MhAroTGbGQeDxzeOJy3zlcwxqOzGUsXNBEpO0qf/kOJb1ZU6ww6HmVTjHgv6XCV6t0vyE/UeY0e8RM80m7NehygXkf+a5nV3RaH0GF3mjnH3O7uPFA3yj12PKaKeXWYiA/TWoU6uRw1/pg5PyHwdHnHjMnYKzu/+NkY43w9sMxakJGc3wPt94v6NoU5g0mM0569lG8ZUFbt8Mt/HPnGWPCw8JdFgl9jktLG9kKLb9LlVGw1GjMfBBBjtRTO11rn1qT7Hay9VI6fUelKjMskrbJJDWmu02FF9V6ta7amA3/+WkPRtivM2qLO64zWWDqRmzyvM0+GgYcLWEpm+fgjSfAI1q+jdVSY5RWduOG4oKC3s9GPrIhzPs8uhccHG0C8p90k3+yQo84CMbvkDQipDNGr5rxygYUxCRH45qCCZymQh6r0MzlWrglUda0WIsWs+wxaJslTlKkQbslWlTqcpFqDDnbkKQiFdYdmumBwaSmouES9r6woHvAaEojHEXRBCM3yVEUTTC6N5wTwAmbsxYKVaEgj+LiBgUZ8oWhuBEF6uHIyr5sWMD9Fa51bAwwmf+Um6yRT7zJv9HCyvjRXoGxAW1hu9+jXuGRjRAUDv7oMpVRX4WTHBZsrhEx7j0zlEqb6v1eskeP1Zo8JWWHOT7nTKzSp05SqF3cAtc3LXWPIfuKhoYjCuHI7gHCv84jTCay2kE4yvjC8dfkr3FfQWHX15z85D+kpmC+wxGhuDEemRDmPSIhmy+I4dEnDF5BUux4/NJRr/HCOuHYkaLR0s5GnfxozOkXlsnap8hvLHa26QYsdNCgS7UrjRpBLnHAzy2cvteehvlaprQ6iH3hcGLBQPAXPDvnWMJXE8zhuK/wGB8udIxEdE4WCvvZ5GQl/xEbuePCo+qCRzOZec5G4c0XtuMKjiFeXdhocSzPabRxBuOY48IDwgmSdUetr4qun0H/pXfbkzpDY99sQx43aL4hu80zZNA04ZQntZ/eY/17n/abN/yHjVGKWXNE4wwUYLHRsNy4GPAYecBwFHw8quN8LE7NRHtiHBgRBCMfiJMTvExB59l8IRwRxjvqYYXByHBbzJFk1MOJqXlcYRCMfGzXqA9bDMehHfKA97gZYcfwjLVRrzkGKV8oDLlxprKBmnioArURn5Ys4AvTER3UFQ4nWHTnpW/lYp5BfvuK8Ogxj8CAE419nEhVGI7dNnnCeRtjg461fkclnuaHBIOjO+Nn8hNQC9ofH8Z+/w+KUyMGibcvugAAAABJRU5ErkJggg==\"/></html>";
    f_logo_label->setText(f_logo_text);
    f_logo_label->setMinimumSize(90, 30);   
    f_logo_label->show();
    layout_row0->addWidget(f_logo_label, -1, Qt::AlignRight);
    
    
    
    QPushButton *testButton = new QPushButton("Test Note", this);
    connect(testButton, SIGNAL(pressed()), this, SLOT(test_press()));
    connect(testButton, SIGNAL(released()), this, SLOT(test_release()));    
        
    layout_row0->addWidget(testButton, -1, Qt::AlignRight);
    
    
    int f_row = 0;
    int f_column = 0;
    
    int f_gb_layout_row = 0;
    int f_gb_layout_column = 0;
    /*Lay out the controls you declared in the first step*/
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Osc1 controls" << endl;    
#endif    
    
    QHBoxLayout *layout_row1 = new QHBoxLayout();
    
    /*The oscillator1 GroupBox*/
    QGroupBox * f_gb_osc1 = newGroupBox("Osc1", this);
    QGridLayout *f_gb_osc1_layout = new QGridLayout(f_gb_osc1);
    
    
    m_osc1_pitch = get_knob(minus12_to_12);
    m_osc1_pitchLabel = newQLabel(this);
    add_widget(f_gb_osc1_layout, f_gb_layout_column, f_gb_layout_row, "Pitch", m_osc1_pitch, m_osc1_pitchLabel);
    connect(m_osc1_pitch, SIGNAL(valueChanged(int)), this, SLOT(osc1PitchChanged(int)));
    osc1PitchChanged(m_osc1_pitch->value());    
    
    /*v_add_knob_to_layout(m_osc1_pitch, minus12_to_12, 0, m_osc1_pitchLabel, f_gb_osc1_layout, QString("Pitch"), 
            f_gb_layout_column, f_gb_layout_row, SIGNAL(valueChanged(int)), SLOT(osc1PitchChanged(int)));*/
    
    f_gb_layout_column++;
    
    m_osc1_tune = get_knob(minus1_to_1);
    m_osc1_tuneLabel = newQLabel(this);
    add_widget(f_gb_osc1_layout, f_gb_layout_column, f_gb_layout_row, "Tune", m_osc1_tune, m_osc1_tuneLabel);
    connect(m_osc1_tune, SIGNAL(valueChanged(int)), this, SLOT(osc1TuneChanged(int)));
    osc1TuneChanged(m_osc1_tune->value());
    
    f_gb_layout_column++;
    
    m_osc1_volume = get_knob(decibels_30_to_0, -6);
    m_osc1_volumeLabel = newQLabel(this);
    add_widget(f_gb_osc1_layout, f_gb_layout_column, f_gb_layout_row, "Vol", m_osc1_volume, m_osc1_volumeLabel);
    connect(m_osc1_volume, SIGNAL(valueChanged(int)), this, SLOT(osc1VolumeChanged(int)));
    osc1VolumeChanged(m_osc1_volume->value());
    
    f_gb_layout_column++;
    
    m_osc1_type = get_combobox(f_osc_types, f_osc_types_count , this);     
    add_widget_no_label(f_gb_osc1_layout, f_gb_layout_column, f_gb_layout_row, "Type", m_osc1_type);
    connect(m_osc1_type, SIGNAL(currentIndexChanged(int)), this, SLOT(osc1TypeChanged(int)));
    osc1TypeChanged(m_osc1_type->currentIndex());
    
    layout_row1->addWidget(f_gb_osc1, -1, Qt::AlignLeft);
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    f_column++;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the ADSR Amp controls" << endl;    
#endif
    
    QGroupBox * f_gb_adsr = newGroupBox("ADSR Amp", this);
    QGridLayout *f_gb_adsr_layout = new QGridLayout(f_gb_adsr);
    
    m_attack = get_knob(zero_to_one);
    m_attackLabel = newQLabel(this);
    add_widget(f_gb_adsr_layout, f_gb_layout_column, f_gb_layout_row, "Attack",m_attack, m_attackLabel);
    connect(m_attack,   SIGNAL(valueChanged(int)), this, SLOT(attackChanged(int)));
    attackChanged  (m_attack->value());
    
    f_gb_layout_column++;
        
    m_decay   =  get_knob(zero_to_one); //newQDial(  1, 100,  1,  25); // s * 100
    m_decayLabel   = newQLabel(this);
    add_widget(f_gb_adsr_layout, f_gb_layout_column, f_gb_layout_row, "Decay",m_decay, m_decayLabel);
    connect(m_decay,   SIGNAL(valueChanged(int)), this, SLOT(decayChanged(int)));
    decayChanged  (m_decay->value());
    
    f_gb_layout_column++;
    
    m_sustain =  get_knob(decibels_30_to_0); // newQDial(  0, 100,  1,  75); // %
    m_sustainLabel = newQLabel(this);
    add_widget(f_gb_adsr_layout, f_gb_layout_column, f_gb_layout_row, "Sustain", m_sustain, m_sustainLabel);    
    connect(m_sustain, SIGNAL(valueChanged(int)), this, SLOT(sustainChanged(int)));
    sustainChanged(m_sustain->value());
    
    f_gb_layout_column++;
    
    m_release = get_knob(zero_to_four); //newQDial(  1, 400, 10, 200); // s * 100
    m_releaseLabel = newQLabel(this);
    add_widget(f_gb_adsr_layout, f_gb_layout_column, f_gb_layout_row, "Release", m_release, m_releaseLabel);
    connect(m_release, SIGNAL(valueChanged(int)), this, SLOT(releaseChanged(int)));
    releaseChanged(m_release->value());
    
    layout_row1->addWidget(f_gb_adsr, -1, Qt::AlignLeft);
    f_column++;
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
        
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Distortion controls" << endl;    
#endif    
    
    QGroupBox * f_gb_dist = newGroupBox("Distortion", this);    
    QGridLayout *f_gb_dist_layout = new QGridLayout(f_gb_dist);
    
    
    m_dist  = newQDial(  -6, 36,  1,  -6); 
    m_distLabel  = new QLabel(this);
    add_widget(f_gb_dist_layout, f_gb_layout_column, f_gb_layout_row, "Gain", m_dist, m_distLabel);
    connect(m_dist,  SIGNAL(valueChanged(int)), this, SLOT(distChanged(int)));
    distChanged (m_dist->value());
    
    f_gb_layout_column++;
    
    m_dist_wet  = get_knob(zero_to_one);    
    add_widget_no_label(f_gb_dist_layout, f_gb_layout_column, f_gb_layout_row, "Wet", m_dist_wet);
    connect(m_dist_wet,  SIGNAL(valueChanged(int)), this, SLOT(distWetChanged(int)));
    distWetChanged (m_dist_wet->value());
    
    layout_row1->addWidget(f_gb_dist, -1, Qt::AlignLeft);
    f_column++;
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the noise controls" << endl;    
#endif    
    
    /*The Noise Amp GroupBox*/
    QGroupBox * f_gb_noise_amp = newGroupBox("Noise", this);    
    QGridLayout *f_gb_noise_amp_layout = new QGridLayout(f_gb_noise_amp);
    
    
    m_noise_amp  = get_knob(decibels_0);
    m_noise_ampLabel  = new QLabel(this);
    add_widget(f_gb_noise_amp_layout, f_column, f_row, "Vol", m_noise_amp, m_noise_ampLabel);
    connect(m_noise_amp,  SIGNAL(valueChanged(int)), this, SLOT(noiseAmpChanged(int)));
    noiseAmpChanged (m_dist ->value());
    
    layout_row1->addWidget(f_gb_noise_amp, -1, Qt::AlignLeft);
    
    /*Start a new row*/
    f_row++;
    f_column = 0;
    
    
    layout->addLayout(layout_row1, -1);    
    
    QHBoxLayout *layout_row2 = new QHBoxLayout();
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Osc2 controls" << endl;    
#endif    
    
    QGroupBox * f_gb_osc2 = newGroupBox("Osc2", this);
    QGridLayout *f_gb_osc2_layout = new QGridLayout(f_gb_osc2);
    
    m_osc2_pitch = get_knob(minus12_to_12);
    m_osc2_pitchLabel = newQLabel(this);
    add_widget(f_gb_osc2_layout, f_gb_layout_column, f_gb_layout_row, "Pitch", m_osc2_pitch, m_osc2_pitchLabel);
    connect(m_osc2_pitch, SIGNAL(valueChanged(int)), this, SLOT(osc2PitchChanged(int)));
    osc2PitchChanged(m_osc2_pitch->value());
            
    f_gb_layout_column++;
    
    m_osc2_tune = get_knob(minus1_to_1);
    m_osc2_tuneLabel = newQLabel(this);
    add_widget(f_gb_osc2_layout, f_gb_layout_column, f_gb_layout_row, "Tune", m_osc2_tune, m_osc2_tuneLabel);
    connect(m_osc2_tune, SIGNAL(valueChanged(int)), this, SLOT(osc2TuneChanged(int)));
    osc2TuneChanged(m_osc2_tune->value());
    
    f_gb_layout_column++;
    
    m_osc2_volume = get_knob(decibels_0, -60);
    m_osc2_volumeLabel = newQLabel(this);
    add_widget(f_gb_osc2_layout, f_gb_layout_column, f_gb_layout_row, "Vol", m_osc2_volume, m_osc2_volumeLabel);
    connect(m_osc2_volume, SIGNAL(valueChanged(int)), this, SLOT(osc2VolumeChanged(int)));
    osc2VolumeChanged(m_osc2_volume->value());
    
    f_gb_layout_column++;
    
    m_osc2_type = get_combobox(f_osc_types, f_osc_types_count , this);     
    add_widget_no_label(f_gb_osc2_layout, f_gb_layout_column, f_gb_layout_row, "Type", m_osc2_type);
    connect(m_osc2_type, SIGNAL(currentIndexChanged(int)), this, SLOT(osc2TypeChanged(int)));
    osc2TypeChanged(m_osc2_type->currentIndex());
    
    layout_row2->addWidget(f_gb_osc2, -1, Qt::AlignLeft);
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    f_column++;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the ADSR Filter controls" << endl;    
#endif    
    
    QGroupBox * f_gb_adsr_f = newGroupBox("ADSR Filter", this);
    QGridLayout *f_gb_adsr_f_layout = new QGridLayout(f_gb_adsr_f);
    
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    
    m_filter_attack = get_knob(zero_to_one);
    m_filter_attackLabel = newQLabel(this);
    add_widget(f_gb_adsr_f_layout, f_gb_layout_column, f_gb_layout_row, "Attack",m_filter_attack, m_filter_attackLabel);
    connect(m_filter_attack,   SIGNAL(valueChanged(int)), this, SLOT(filterAttackChanged(int)));
    //filterAttackChanged  (m_filter_attack  ->value());
    
    f_gb_layout_column++;
        
    m_filter_decay   =  get_knob(zero_to_one); //newQDial(  1, 100,  1,  25); // s * 100
    m_filter_decayLabel   = newQLabel(this);
    add_widget(f_gb_adsr_f_layout, f_gb_layout_column, f_gb_layout_row, "Decay",m_filter_decay, m_filter_decayLabel);
    connect(m_filter_decay,   SIGNAL(valueChanged(int)), this, SLOT(filterDecayChanged(int)));
    //filterDecayChanged  (m_filter_decay ->value());
    
    f_gb_layout_column++;
    
    m_filter_sustain =  get_knob(zero_to_one); // newQDial(  0, 100,  1,  75); // %
    m_filter_sustainLabel = newQLabel(this);
    add_widget(f_gb_adsr_f_layout, f_gb_layout_column, f_gb_layout_row, "Sustain", m_filter_sustain, m_filter_sustainLabel);
    connect(m_filter_sustain, SIGNAL(valueChanged(int)), this, SLOT(filterSustainChanged(int)));
    //filterSustainChanged(m_filter_sustain->value());
    
    f_gb_layout_column++;
    
    m_filter_release = get_knob(zero_to_four); //newQDial(  1, 400, 10, 200); // s * 100
    m_filter_releaseLabel = newQLabel(this);
    add_widget(f_gb_adsr_f_layout, f_gb_layout_column, f_gb_layout_row, "Release", m_filter_release, m_filter_releaseLabel);
    connect(m_filter_release, SIGNAL(valueChanged(int)), this, SLOT(filterReleaseChanged(int)));    
    //filterReleaseChanged(m_filter_release->value());
        
    layout_row2->addWidget(f_gb_adsr_f, -1, Qt::AlignLeft);
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    f_column++;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Filter controls" << endl;    
#endif    
    
    QGroupBox * f_gb_filter = newGroupBox("LP Filter", this); 
    QGridLayout *f_gb_filter_layout = new QGridLayout(f_gb_filter);
    
    m_timbre  =  get_knob(pitch);  //newQDial(  39, 136,  1,  82); // s * 100
    m_timbreLabel  = newQLabel(this);
    add_widget(f_gb_filter_layout, f_gb_layout_column, f_gb_layout_row, "Cutoff",m_timbre, m_timbreLabel);
    connect(m_timbre,  SIGNAL(valueChanged(int)), this, SLOT(timbreChanged(int)));
    //timbreChanged (m_timbre ->value());
    
    f_gb_layout_column++;
    
    m_res  =  get_knob(decibels_30_to_0); 
    m_resLabel  = newQLabel(this);
    add_widget(f_gb_filter_layout, f_gb_layout_column, f_gb_layout_row, "Res", m_res, m_resLabel);
    connect(m_res,  SIGNAL(valueChanged(int)), this, SLOT(resChanged(int)));
    //resChanged (m_res ->value());
    
    f_gb_layout_column++;
    
    m_filter_env_amt  =  get_knob(minus36_to_36); 
    m_filter_env_amtLabel  = newQLabel(this);
    add_widget(f_gb_filter_layout, f_gb_layout_column, f_gb_layout_row, "Env", m_filter_env_amt, m_filter_env_amtLabel);
    connect(m_filter_env_amt,  SIGNAL(valueChanged(int)), this, SLOT(filterEnvAmtChanged(int)));
    //filterEnvAmtChanged (m_filter_env_amt ->value());
    
    layout_row2->addWidget(f_gb_filter, -1, Qt::AlignLeft);
    f_column++;
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    
    layout->addLayout(layout_row2, -1);
    
    QHBoxLayout *layout_row3 = new QHBoxLayout();
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Master controls" << endl;    
#endif    
    
    QGroupBox * f_gb_master_vol = newGroupBox("Master", this); 
    QGridLayout *f_gb_master_vol_layout = new QGridLayout(f_gb_master_vol);
    
    m_master_volume  =  get_knob(decibels_plus_12);
    m_master_volumeLabel  = newQLabel(this);
    add_widget(f_gb_master_vol_layout, f_gb_layout_column, f_gb_layout_row, "Volume",m_master_volume, m_master_volumeLabel);
    connect(m_master_volume,  SIGNAL(valueChanged(int)), this, SLOT(masterVolumeChanged(int)));
    //masterVolumeChanged (m_master_volume ->value());
    
    f_gb_layout_column++;
    
    m_master_unison_voices  =  newQDial(1, 7, 1, 1);
    m_master_unison_voicesLabel  = newQLabel(this);
    add_widget(f_gb_master_vol_layout, f_gb_layout_column, f_gb_layout_row, "Unison",m_master_unison_voices, m_master_unison_voicesLabel);
    connect(m_master_unison_voices,  SIGNAL(valueChanged(int)), this, SLOT( masterUnisonVoicesChanged(int)));
    //masterUnisonVoicesChanged (m_master_unison_voices ->value());
    
    f_gb_layout_column++;
    
    m_master_unison_spread  =  get_knob(zero_to_one);
    m_master_unison_spreadLabel  = newQLabel(this);
    add_widget(f_gb_master_vol_layout, f_gb_layout_column, f_gb_layout_row, "Spread",m_master_unison_spread, m_master_unison_spreadLabel);
    connect(m_master_unison_spread,  SIGNAL(valueChanged(int)), this, SLOT(masterUnisonSpreadChanged(int)));
    //masterUnisonSpreadChanged (m_master_unison_spread ->value());
    
    f_gb_layout_column++;
    
    m_master_glide  =  get_knob(zero_to_one);
    m_master_glideLabel  = newQLabel(this);
    add_widget(f_gb_master_vol_layout, f_gb_layout_column, f_gb_layout_row, "Glide",m_master_glide, m_master_glideLabel);
    connect(m_master_glide,  SIGNAL(valueChanged(int)), this, SLOT(masterGlideChanged(int)));
    //masterGlideChanged (m_master_glide ->value());
    
    f_gb_layout_column++;
    
    m_master_pitchbend_amt  =  newQDial(1, 36, 1, 2);
    m_master_pitchbend_amtLabel  = newQLabel(this);
    add_widget(f_gb_master_vol_layout, f_gb_layout_column, f_gb_layout_row, "Pitchbend",m_master_pitchbend_amt, m_master_pitchbend_amtLabel);
    connect(m_master_pitchbend_amt,  SIGNAL(valueChanged(int)), this, SLOT(masterPitchbendAmtChanged(int)));
    //masterPitchbendAmtChanged (m_master_pitchbend_amt ->value());
    
    f_gb_layout_column++;
    
    
    layout_row3->addWidget(f_gb_master_vol, -1, Qt::AlignLeft);
    f_column++;
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "Creating the Pitch Envelope controls" << endl;    
#endif    
    
    QGroupBox * f_gb_pitch_env = newGroupBox("Pitch Envelope", this); 
    QGridLayout *f_gb_pitch_env_layout = new QGridLayout(f_gb_pitch_env);
    
    
    m_pitch_env_amt = get_knob(minus36_to_36, 0);
    m_pitch_env_amtLabel = newQLabel(this);
    add_widget(f_gb_pitch_env_layout, f_gb_layout_column, f_gb_layout_row, "Amount", m_pitch_env_amt, m_pitch_env_amtLabel);
    connect(m_pitch_env_amt, SIGNAL(valueChanged(int)), this, SLOT(pitchEnvAmtChanged(int)));
    //pitchEnvAmtChanged(m_pitch_env_amt->value());
    
    f_gb_layout_column++;
    
    m_pitch_env_time = get_knob(zero_to_two, 0);
    m_pitch_env_timeLabel = newQLabel(this);
    add_widget(f_gb_pitch_env_layout, f_gb_layout_column, f_gb_layout_row, "Time", m_pitch_env_time, m_pitch_env_timeLabel);
    connect(m_pitch_env_time, SIGNAL(valueChanged(int)), this, SLOT(pitchEnvTimeChanged(int)));
   //pitchEnvTimeChanged(m_pitch_env_time->value());
    
    layout_row3->addWidget(f_gb_pitch_env, -1, Qt::AlignLeft);
    f_column++;
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
        
    QGroupBox * f_gb_lfo = newGroupBox("LFO", this); 
    QGridLayout *f_gb_lfo_layout = new QGridLayout(f_gb_lfo);
    
    f_column++;
    
    f_gb_layout_row = 0;
    f_gb_layout_column = 0;
    
    m_lfo_freq  =  newQDial(10,400,1,100);
    m_lfo_freqLabel  = newQLabel(this);
    add_widget(f_gb_lfo_layout, f_gb_layout_column, f_gb_layout_row, "Freq", m_lfo_freq, m_lfo_freqLabel);
    connect(m_lfo_freq,  SIGNAL(valueChanged(int)), this, SLOT(LFOfreqChanged(int)));
    
    f_gb_layout_column++;
    
    m_lfo_type = get_combobox(f_lfo_types, f_lfo_types_count, this);     
    add_widget_no_label(f_gb_lfo_layout, f_gb_layout_column, f_gb_layout_row, "Type", m_lfo_type);
    connect(m_lfo_type, SIGNAL(currentIndexChanged(int)), this, SLOT(LFOtypeChanged(int)));
    //LFOtypeChanged(m_lfo_type->currentIndex());
    
    f_gb_layout_column++;
    
    m_lfo_amp  =  newQDial(-24,24,1,0);
    m_lfo_ampLabel  = newQLabel(this);
    add_widget(f_gb_lfo_layout, f_gb_layout_column, f_gb_layout_row, "Amp", m_lfo_amp, m_lfo_ampLabel);
    connect(m_lfo_amp,  SIGNAL(valueChanged(int)), this, SLOT(LFOampChanged(int)));
    
    f_gb_layout_column++;
    
    m_lfo_pitch  =  newQDial(-36,36,1,0);
    m_lfo_pitchLabel  = newQLabel(this);
    add_widget(f_gb_lfo_layout, f_gb_layout_column, f_gb_layout_row, "Pitch", m_lfo_pitch, m_lfo_pitchLabel);
    connect(m_lfo_pitch,  SIGNAL(valueChanged(int)), this, SLOT(LFOpitchChanged(int)));
    
    f_gb_layout_column++;
    
    m_lfo_cutoff  =  newQDial(-48,48,1,0);
    m_lfo_cutoffLabel  = newQLabel(this);
    add_widget(f_gb_lfo_layout, f_gb_layout_column, f_gb_layout_row, "Cutoff", m_lfo_cutoff, m_lfo_cutoffLabel);
    connect(m_lfo_cutoff,  SIGNAL(valueChanged(int)), this, SLOT(LFOcutoffChanged(int)));    
    
    layout_row3->addWidget(f_gb_lfo, -1, Qt::AlignLeft);
    layout->addLayout(layout_row3, -1);
        
    /*End test button code, DO NOT remove the code below this*/

    QTimer *myTimer = new QTimer(this);
    connect(myTimer, SIGNAL(timeout()), this, SLOT(oscRecv()));
    myTimer->setSingleShot(false);
    myTimer->start(0);
    
    m_suppressHostUpdate = false;

}

/*I'm leaving this in here for now, but at the present it doesn't work*/
void SynthGUI::v_add_knob_to_layout(QDial * a_knob, e_knob_type a_knob_type, int a_default_value, QLabel * a_label, QGridLayout * a_layout, QString a_title,
int a_gb_layout_column, int a_gb_layout_row, const char * a_signal, const char * a_slot)
{
    a_knob = get_knob(a_knob_type, a_default_value);
    a_label  = newQLabel(this);
    add_widget(a_layout, a_gb_layout_column, a_gb_layout_row, a_title,a_knob, a_label);
    connect(a_knob,  a_signal, this, a_slot);    
}


void SynthGUI::add_widget(QGridLayout * a_layout, int a_position_x, int a_position_y, QString a_label_text,  QWidget * a_widget,
    QLabel * a_label)
{   
    QLabel * f_knob_title = new QLabel(a_label_text,  this);
    f_knob_title->setMinimumWidth(60);  //TODO:  make this a constant
    f_knob_title->setAlignment(Qt::AlignCenter);
    f_knob_title->setStyleSheet("background-color: white; border: 1px solid black;  border-radius: 6px;");  //TODO:  make this a constant string for all knobs
    
    a_layout->addWidget(f_knob_title, a_position_y, a_position_x, Qt::AlignCenter);    
    a_layout->addWidget(a_widget,  (a_position_y + 1), a_position_x);
    a_layout->addWidget(a_label,  (a_position_y + 2), a_position_x, Qt::AlignCenter);     
}

void SynthGUI::add_widget_no_label(QGridLayout * a_layout, int a_position_x, int a_position_y, QString a_label_text, QWidget * a_widget)
{
    QLabel * f_knob_title = new QLabel(a_label_text,  this);
    f_knob_title->setMinimumWidth(60);  //TODO:  make this a constant
    f_knob_title->setAlignment(Qt::AlignCenter);
    f_knob_title->setStyleSheet("background-color: white; border: 1px solid black;  border-radius: 6px;");    //TODO:  make this a constant string for all knobs
    
    a_layout->addWidget(f_knob_title, a_position_y, a_position_x, Qt::AlignCenter);    
    a_layout->addWidget(a_widget,  (a_position_y + 1), a_position_x);    
}

QGroupBox * SynthGUI::newGroupBox(QString a_title, QWidget * a_parent)
{
    QGroupBox * f_result = new QGroupBox(a_parent);
    
    f_result->setTitle(a_title);
    f_result->setAlignment(Qt::AlignHCenter);
    return f_result;
}

QLabel * SynthGUI::newQLabel(QWidget * a_parent)
{
    QLabel * f_result = new QLabel(a_parent);
    //_result->setStyleSheet("background-color: white; border: 2px solid black;  border-radius: 6px;");
    return f_result;
}

QDial * SynthGUI::get_knob(e_knob_type a_ktype, int a_default_value)
{
    int f_min, f_max, f_step, f_value;
    
    switch(a_ktype)
    {
        case decibels_0:
                f_min = -60; f_max = 0; f_step = 1; f_value = -6; 
                break;
        case decibels_plus_12:
            f_min = -60; f_max = 12; f_step = 1; f_value = -6;            
            break;
        case decibels_plus_24:
            f_min = -60; f_max = 24; f_step = 1; f_value = -6;            
            break;
        case decibels_plus_6:            
            f_min = -60; f_max = 6; f_step = 1; f_value = -6;            
            break;
        case decibels_30_to_0:
            f_min = -30; f_max = 0; f_step = 1; f_value = -9;            
            break;
        case pitch:
            f_min = 20; f_max = 124; f_step = 1; f_value = 105;            
            break;
        case zero_to_four:
            f_min = 1; f_max = 400; f_step = 4; f_value = 75;            
            break;
        case zero_to_one:
            f_min = 1; f_max = 100; f_step = 1; f_value = 15;            
            break;
        case zero_to_two:
            f_min = 1; f_max = 200; f_step = 2; f_value = 25;            
            break;
        case minus1_to_1:
            f_min = -100; f_max = 100; f_step = 1; f_value = 0;            
            break;
        case minus12_to_12:
            f_min = -12; f_max = 12; f_step = 1; f_value = 0;            
            break;
        case minus24_to_24:
            f_min = -24; f_max = 24; f_step = 1; f_value = 0;            
            break;
        case minus36_to_36:
            f_min = -36; f_max = 36; f_step = 1; f_value = 0;            
            break;
    }
    
    if(a_default_value != 333)  //This makes the assumption that we will never pick 333 as a default value
    {
        f_value = a_default_value;
    }
    
     return newQDial(f_min, f_max, f_step, f_value);
    
}

QCheckBox * SynthGUI::get_checkbox(std::string a_text)
{
    QCheckBox * f_checkbox = new QCheckBox(this);
    
    f_checkbox->setText(QString::fromStdString(a_text));
    
    //TODO:  add a skin to make it look like a toggle-switch
        
    return f_checkbox;
}


QDial * SynthGUI::newQDial( int minValue, int maxValue, int pageStep, int value )
{
    QDial *dial = new QDial( this );
    dial->setMinimum( minValue );
    dial->setMaximum( maxValue );
    dial->setPageStep( pageStep );
    dial->setValue( value );
    dial->setNotchesVisible(false); 
    //TODO:  Make this a constant value
    dial->setMaximumHeight(66);
    dial->setMaximumWidth(66);
    dial->setMinimumHeight(66);
    dial->setMinimumWidth(66);
    
    //dial->setFocusPolicy(Qt::NoFocus);
    
    return dial;
}

QComboBox * SynthGUI::get_combobox(QString a_choices [], int a_count,  QWidget * a_parent)
{
    QComboBox * f_result = new QComboBox(a_parent);
    QStringList f_items;
    
    for(int i = 0; i < a_count; i++)
    {
        f_items << a_choices[i];
    }
    
    f_result->addItems(f_items);
    
    return f_result;
}

/*Implement the event handlers from step 2.*/
void SynthGUI::setAttack(float sec)
{
    m_suppressHostUpdate = true;
    m_attack->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setDecay(float sec)
{
    m_suppressHostUpdate = true;
    m_decay->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setSustain(float val)
{
    m_suppressHostUpdate = true;
    m_sustain->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setRelease(float sec)
{
    m_suppressHostUpdate = true;
    m_release->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setTimbre(float val)
{
    m_suppressHostUpdate = true;
    m_timbre->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setRes(float val)
{
    m_suppressHostUpdate = true;
    m_res->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setDist(float val)
{
    m_suppressHostUpdate = true;
    m_dist->setValue(int(val)); 
    m_suppressHostUpdate = false;
}

void SynthGUI::setFilterAttack (float sec)
{    
    m_suppressHostUpdate = true;
    m_filter_attack->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setFilterDecay  (float sec)
{
    m_suppressHostUpdate = true;
    m_filter_decay->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setFilterSustain(float val)
{
    m_suppressHostUpdate = true;
    m_filter_sustain->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setFilterRelease(float sec)
{
    m_suppressHostUpdate = true;
    m_filter_release->setValue(int(sec));
    m_suppressHostUpdate = false;
}

void SynthGUI::setNoiseAmp(float val)
{
    m_suppressHostUpdate = true;
    m_noise_amp->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setFilterEnvAmt(float val)
{
    m_suppressHostUpdate = true;
    m_filter_env_amt->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setDistWet(float val)
{
    m_suppressHostUpdate = true;
    m_dist_wet->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc1Type(float val)
{
    m_suppressHostUpdate = true;
    m_osc1_type->setCurrentIndex(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc1Pitch(float val)
{
    m_suppressHostUpdate = true;
    m_osc1_pitch->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc1Tune(float val)
{
    m_suppressHostUpdate = true;
    m_osc1_tune->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc1Volume(float val)
{
    m_suppressHostUpdate = true;
    m_osc1_volume->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc2Type(float val)
{
    m_suppressHostUpdate = true;
    m_osc2_type->setCurrentIndex(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc2Pitch(float val)
{
    m_suppressHostUpdate = true;
    m_osc2_pitch->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc2Tune(float val)
{
    m_suppressHostUpdate = true;
    m_osc2_tune->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setOsc2Volume(float val)
{
    m_suppressHostUpdate = true;
    m_osc2_volume->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setMasterVolume(float val)
{
    m_suppressHostUpdate = true;
    m_master_volume->setValue(int(val));
    m_suppressHostUpdate = false;
}

/*Begin new stuff*/

void SynthGUI::setMasterUnisonVoices(float val)
{
    m_suppressHostUpdate = true;
    m_master_unison_voices->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setMasterUnisonSpread(float val)
{
    m_suppressHostUpdate = true;
    m_master_unison_spread->setValue(int(val));
    m_suppressHostUpdate = false; 
}

void SynthGUI::setMasterGlide(float val)
{
    m_suppressHostUpdate = true;
    m_master_glide->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setMasterPitchbendAmt(float val)
{
    m_suppressHostUpdate = true;
    m_master_pitchbend_amt->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setPitchEnvAmt(float val)
{
    m_suppressHostUpdate = true;
    m_pitch_env_amt->setValue(int(val));
    m_suppressHostUpdate = false;
}


void SynthGUI::setPitchEnvTime(float val)
{
    m_suppressHostUpdate = true;
    m_pitch_env_time->setValue(int(val));
    m_suppressHostUpdate = false;
}


/*
void SynthGUI::setBank(int val)
{
    cerr << "setBank called with val: " << val << endl;
}
*/


void SynthGUI::setProgram(float val)
{
#ifdef LMS_DEBUG_MODE_QT
    cerr << "setProgram called with val: " << val << endl;
#endif
    m_suppressHostUpdate = true;
    m_program->setCurrentIndex(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setLFOfreq(float val)
{
    m_suppressHostUpdate = true;
    m_lfo_freq->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setLFOtype(float val)
{
    m_suppressHostUpdate = true;
    m_lfo_type->setCurrentIndex(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setLFOamp(float val)
{
    m_suppressHostUpdate = true;
    m_lfo_amp->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setLFOpitch(float val)
{
    m_suppressHostUpdate = true;
    m_lfo_pitch->setValue(int(val));
    m_suppressHostUpdate = false;
}

void SynthGUI::setLFOcutoff(float val)
{
    m_suppressHostUpdate = true;
    m_lfo_cutoff->setValue(int(val));
    m_suppressHostUpdate = false;
}

/*Standard handlers for the audio slots, these perform manipulations of knob values
 that are common in audio applications*/

void SynthGUI::changed_zero_to_x(int a_value, QLabel * a_label, int a_port)
{
    float val = float(a_value) * .01;
    a_label->setText(QString("%1").arg(val));
    
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", a_port, float(a_value));     
    }
}

void SynthGUI::changed_integer(int a_value, QLabel * a_label, int a_port)
{
    float val = float(a_value);
    a_label->setText(QString("%1").arg(val));
    
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", a_port, val);
    }
}

void SynthGUI::changed_seconds(int a_value, QLabel * a_label, int a_port)
{
    float sec = float(a_value) * .01;
    a_label->setText(QString("%1").arg(sec));
    
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", a_port, float(a_value));
    }
}

void SynthGUI::changed_pitch(int a_value, QLabel * a_label, int a_port)
{
    /*We need to send midi note number to the synth, as it probably still needs to process it as
     midi_note number.  We use this to display hz to the user*/
    
    float f_value = float(a_value);
    float f_hz = f_pit_midi_note_to_hz(f_value);
    
    a_label->setText(QString("%1 hz").arg((int)f_hz));
    
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", a_port, f_value);     
    }    
}

void SynthGUI::changed_decibels(int a_value, QLabel * a_label, int a_port)
{
    /*Decibels is a reasonable way to display this to the user, so just use it as it is*/
    a_label->setText(QString("%1").arg(a_value));
    
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", a_port, float(a_value));
    }
}




/*Implement the event handlers from step 3.*/

void SynthGUI::attackChanged(int value)
{
    changed_seconds(value,m_attackLabel,LMS_ATTACK);
}

void
SynthGUI::decayChanged(int value)
{
    changed_seconds(value,m_decayLabel,LMS_DECAY);
}

void SynthGUI::sustainChanged(int value)
{
    changed_decibels(value, m_sustainLabel, LMS_SUSTAIN);    
}

void SynthGUI::releaseChanged(int value)
{
    changed_seconds(value, m_releaseLabel, LMS_RELEASE);    
}

void SynthGUI::timbreChanged(int value)
{
    changed_pitch(value, m_timbreLabel, LMS_TIMBRE);    
}

void SynthGUI::resChanged(int value)
{
    changed_decibels(value, m_resLabel, LMS_RES);    
}

void SynthGUI::distChanged(int value)
{
    changed_integer(value, m_distLabel, LMS_DIST);
}


void SynthGUI::filterAttackChanged(int value)
{
    changed_seconds(value,m_filter_attackLabel,LMS_FILTER_ATTACK);
}

void
SynthGUI::filterDecayChanged(int value)
{
    changed_seconds(value,m_filter_decayLabel,LMS_FILTER_DECAY);
}

void SynthGUI::filterSustainChanged(int value)
{
    changed_zero_to_x(value, m_filter_sustainLabel, LMS_FILTER_SUSTAIN);    
}

void SynthGUI::filterReleaseChanged(int value)
{
    changed_seconds(value, m_filter_releaseLabel, LMS_FILTER_RELEASE);    
}

void SynthGUI::noiseAmpChanged(int value)
{
    changed_decibels(value, m_noise_ampLabel, LMS_NOISE_AMP);
}

void SynthGUI::filterEnvAmtChanged(int value)
{
    float val = float(value); // / 100.0;
    m_filter_env_amtLabel->setText(QString("%1").arg(val));

    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", LMS_FILTER_ENV_AMT, val);
    }
}

void SynthGUI::distWetChanged(int value)
{
    //TODO:  make a "Changed no label" method
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", LMS_DIST_WET, (float(value)));
    }
}

void SynthGUI::osc1TypeChanged(int value)
{
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", LMS_OSC1_TYPE, float(value));
    }
}

void SynthGUI::osc1PitchChanged(int value)
{
    changed_integer(value, m_osc1_pitchLabel, LMS_OSC1_PITCH);
}

void SynthGUI::osc1TuneChanged(int value)
{
    changed_zero_to_x(value, m_osc1_tuneLabel, LMS_OSC1_TUNE);
}

void SynthGUI::osc1VolumeChanged(int value)
{
    changed_decibels(value, m_osc1_volumeLabel, LMS_OSC1_VOLUME);
}

void SynthGUI::osc2TypeChanged(int value)
{
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", LMS_OSC2_TYPE, float(value));
    }
}

void SynthGUI::osc2PitchChanged(int value)
{
    changed_integer(value, m_osc2_pitchLabel, LMS_OSC2_PITCH);
}

void SynthGUI::osc2TuneChanged(int value)
{
    changed_zero_to_x(value, m_osc2_tuneLabel, LMS_OSC2_TUNE);
}

void SynthGUI::osc2VolumeChanged(int value)
{
    changed_decibels(value, m_osc2_volumeLabel, LMS_OSC2_VOLUME);
}

void SynthGUI::masterVolumeChanged(int value)
{
    changed_decibels(value, m_master_volumeLabel, LMS_MASTER_VOLUME);
}




void SynthGUI::masterUnisonVoicesChanged(int value)
{
    changed_integer(value, m_master_unison_voicesLabel, LMS_MASTER_UNISON_VOICES);
}


void SynthGUI::masterUnisonSpreadChanged(int value)
{    
    changed_zero_to_x(value, m_master_unison_spreadLabel, LMS_MASTER_UNISON_SPREAD);
}


void SynthGUI::masterGlideChanged(int value)
{
    changed_zero_to_x(value, m_master_glideLabel, LMS_MASTER_GLIDE);
}


void SynthGUI::masterPitchbendAmtChanged(int value)
{
    changed_integer(value, m_master_pitchbend_amtLabel, LMS_MASTER_PITCHBEND_AMT);
}

void SynthGUI::pitchEnvAmtChanged(int value)
{
    changed_integer(value, m_pitch_env_amtLabel, LMS_PITCH_ENV_AMT);
}

void SynthGUI::pitchEnvTimeChanged(int value)
{
    changed_seconds(value, m_pitch_env_timeLabel, LMS_PITCH_ENV_TIME);
}

void SynthGUI::LFOfreqChanged(int a_value)
{
    changed_zero_to_x(a_value, m_lfo_freqLabel, LMS_LFO_FREQ);
}

void SynthGUI::LFOtypeChanged(int a_value)
{
    if (!m_suppressHostUpdate) {
	lo_send(m_host, m_controlPath, "if", LMS_LFO_TYPE, float(a_value));
    }
}

void SynthGUI::LFOampChanged(int a_value)
{
    changed_integer(a_value, m_lfo_ampLabel, LMS_LFO_AMP);
}

void SynthGUI::LFOpitchChanged(int a_value)
{
    changed_integer(a_value, m_lfo_pitchLabel, LMS_LFO_PITCH);
}

void SynthGUI::LFOcutoffChanged(int a_value)
{
    changed_integer(a_value, m_lfo_cutoffLabel, LMS_LFO_FILTER);
}

/*
void SynthGUI::bankChanged(int value)
{
    cerr << "Bank change not yet implemented.  Bank# " << value << endl;
}
*/

void SynthGUI::programChanged(int value)
{    
    /*We intentionally leave the first preset empty*/
    if(value == 0)
        return;

#ifdef LMS_DEBUG_MODE_QT    
    cerr << "programChanged called with value " << value << endl;
#endif    
    
    if(m_suppressHostUpdate)
        return;

    if(presets_tab_delimited[value].compare("empty") != 0)
    {
        QStringList f_preset_values = presets_tab_delimited[value].split("\t");
        //TODO:  change f_i back to zero when there is something at that index
        for(int f_i = LMS_FIRST_CONTROL_PORT; f_i < LMS_LAST_CONTROL_PORT; f_i++)
        {
            if(f_i > f_preset_values.count())
            {
#ifdef LMS_DEBUG_MODE_QT
                cerr << "programChanged:  f_i is greater than f_preset_values.count(), preset not fully loaded.\n";
#endif
                break;
            }
            /*TODO:  Some error handling here to prevent index-out-of-bounds exceptions from crashing the GUI*/
            int f_preset_value_int = f_preset_values.at(f_i).toInt();
#ifdef LMS_DEBUG_MODE_QT
                cerr << "programChanged:  modifying control.\n";
#endif            
            v_set_control(f_i, f_preset_value_int);
            v_control_changed(f_i, f_preset_value_int, false);
        }
    }    
}
    
void SynthGUI::programSaved()
{
    int f_compare_text = m_program->currentText().compare("empty");
    
    if((m_program->currentIndex()) == 0)
    {
        QMessageBox * f_qmess = new QMessageBox(this);
        
        QString * f_compare_text_string = new QString();
        f_compare_text_string->setNum(f_compare_text);
        
        f_compare_text_string->append("  \"" + presets_tab_delimited[m_program->currentIndex()] + "\"\n" +
        "The first preset on the list must be empty, please select another preset to save.");
        
        f_qmess->setText(*f_compare_text_string);
        f_qmess->show();        
    }
    else if(f_compare_text == 0)
    {
        QMessageBox * f_qmess = new QMessageBox(this);
        
        QString * f_compare_text_string = new QString();
        f_compare_text_string->setNum(f_compare_text);
        
        f_compare_text_string->append("  \"" + presets_tab_delimited[m_program->currentIndex()] + "\"\n" +
        "You must change the name of the preset before you can save it.");
        
        f_qmess->setText(*f_compare_text_string);
        f_qmess->show();
    }    
    else
    {
        QString f_result = m_program->currentText();                
        
        //TODO:  change f_i back to zero when there is something at that index
        for(int f_i = LMS_FIRST_CONTROL_PORT; f_i < LMS_LAST_CONTROL_PORT; f_i++)
        {
            QString * f_number = new QString();
            f_number->setNum(i_get_control(f_i));
            f_result.append("\t");  
            f_result.append(f_number);
        }
                
        presets_tab_delimited[m_program->currentIndex()] = f_result;
        
        QString * f_result2 = new QString();
        
        for(int f_i = 0; f_i < 128; f_i++)
        {
            f_result2->append(presets_tab_delimited[f_i] + "\n");
        }
        
        QFile * f_preset_file = new QFile(QDir::homePath() + "/dssi/" + LMS_PLUGIN_NAME + "-presets.tsv");
        
        f_preset_file->open(QIODevice::WriteOnly);
        
        f_preset_file->write(f_result2->toUtf8());
        f_preset_file->flush();
        
        f_preset_file->close();
                
        m_program->setItemText(m_program->currentIndex(), m_program->currentText());
    }
}

void SynthGUI::v_print_port_name_to_cerr(int a_port)
{
#ifdef LMS_DEBUG_MODE_QT
    switch (a_port) {
    case LMS_ATTACK:
	cerr << "LMS_ATTACK";
	break;
    case LMS_DECAY:
	cerr << "LMS_DECAY";
	break;
    case LMS_SUSTAIN:
	cerr << "LMS_SUSTAIN";
	break;
    case LMS_RELEASE:
	cerr << "LMS_RELEASE";
	break;
    case LMS_TIMBRE:
	cerr << "LMS_TIMBRE";
	break;
    case LMS_RES:
	cerr << "LMS_RES";
	break;        
    case LMS_DIST:
	cerr << "LMS_DIST";
	break;
    case LMS_FILTER_ATTACK:
	cerr << "LMS_FILTER_ATTACK";
	break;
    case LMS_FILTER_DECAY:
	cerr << "LMS_FILTER_DECAY";
	break;
    case LMS_FILTER_SUSTAIN:
	cerr << "LMS_FILTER_SUSTAIN";
	break;
    case LMS_FILTER_RELEASE:
	cerr << "LMS_FILTER_RELEASE";
	break;
    case LMS_NOISE_AMP:
        cerr << "LMS_NOISE_AMP";
        break;    
    case LMS_DIST_WET:
        cerr << "LMS_DIST_WET";
        break;            
    case LMS_FILTER_ENV_AMT:
        cerr << "LMS_FILTER_ENV_AMT";
        break;    
    case LMS_OSC1_TYPE:
        cerr << "LMS_OSC1_TYPE";
        break;            
    case LMS_OSC1_PITCH:
        cerr << "LMS_OSC1_PITCH";
        break;    
    case LMS_OSC1_TUNE:
        cerr << "LMS_OSC1_TUNE";
        break;    
    case LMS_OSC1_VOLUME:
        cerr << "LMS_OSC1_VOLUME";
        break;        
    case LMS_OSC2_TYPE:
        cerr << "LMS_OSC2_TYPE";
        break;            
    case LMS_OSC2_PITCH:
        cerr << "LMS_OSC2_PITCH";
        break;    
    case LMS_OSC2_TUNE:
        cerr << "LMS_OSC2_TUNE";
        break;    
    case LMS_OSC2_VOLUME:
        cerr << "LMS_OSC2_VOLUME";
        break;        
    case LMS_MASTER_VOLUME:
        cerr << "LMS_MASTER_VOLUME";
        break;        
    case LMS_MASTER_UNISON_VOICES:
        cerr << "LMS_MASTER_UNISON_VOICES";
        break;
    case LMS_MASTER_UNISON_SPREAD:
        cerr << "LMS_MASTER_UNISON_SPREAD";
        break;
    case LMS_MASTER_GLIDE:
        cerr << "LMS_MASTER_GLIDE";
        break;
    case LMS_MASTER_PITCHBEND_AMT:
        cerr << "LMS_MASTER_PITCHBEND_AMT";
        break;
    case LMS_PITCH_ENV_AMT:
        cerr << "LMS_PITCH_ENV_AMT ";
        break;
    case LMS_PITCH_ENV_TIME:
        cerr << "LMS_PITCH_ENV_TIME ";
        break;        
    case LMS_PROGRAM_CHANGE:
        cerr << "LMS_PROGRAM_CHANGE ";
        break;
    default:
	cerr << "Warning: received request to set nonexistent port " << a_port ;
        break;
    }
#endif
}

void SynthGUI::v_set_control(int a_port, float a_value)
{

#ifdef LMS_DEBUG_MODE_QT    
    cerr << "v_set_control called.  ";  
    v_print_port_name_to_cerr(a_port);
    cerr << "  value: " << a_value << endl;
#endif
    
    /*Add the controls you created to the control handler*/
    
    switch (a_port) {
    case LMS_ATTACK:
	setAttack(a_value);
	break;
    case LMS_DECAY:
	setDecay(a_value);
	break;
    case LMS_SUSTAIN:
	setSustain(a_value);
	break;
    case LMS_RELEASE:
	setRelease(a_value);
	break;
    case LMS_TIMBRE:
	setTimbre(a_value);
	break;
    case LMS_RES:
	setRes(a_value);
	break;        
    case LMS_DIST:
	setDist(a_value);
	break;
    case LMS_FILTER_ATTACK:
	setFilterAttack(a_value);
	break;
    case LMS_FILTER_DECAY:
	setFilterDecay(a_value);
	break;
    case LMS_FILTER_SUSTAIN:
	setFilterSustain(a_value);
	break;
    case LMS_FILTER_RELEASE:
	setFilterRelease(a_value);
	break;
    case LMS_NOISE_AMP:
        setNoiseAmp(a_value);
        break;    
    case LMS_DIST_WET:
        setDistWet(a_value);
        break;            
    case LMS_FILTER_ENV_AMT:
        setFilterEnvAmt(a_value);
        break;    
    case LMS_OSC1_TYPE:
        setOsc1Type(a_value);
        break;            
    case LMS_OSC1_PITCH:
        setOsc1Pitch(a_value);
        break;    
    case LMS_OSC1_TUNE:
        setOsc1Tune(a_value);
        break;    
    case LMS_OSC1_VOLUME:
        setOsc1Volume(a_value);
        break;        
    case LMS_OSC2_TYPE:
        setOsc2Type(a_value);
        break;            
    case LMS_OSC2_PITCH:
        setOsc2Pitch(a_value);
        break;    
    case LMS_OSC2_TUNE:
        setOsc2Tune(a_value);
        break;    
    case LMS_OSC2_VOLUME:
        setOsc2Volume(a_value);
        break;        
    case LMS_MASTER_VOLUME:
        setMasterVolume(a_value);
        break;    
    case LMS_MASTER_UNISON_VOICES:
        setMasterUnisonVoices(a_value);
        break;
    case LMS_MASTER_UNISON_SPREAD:
        setMasterUnisonSpread(a_value);
        break;
    case LMS_MASTER_GLIDE:
        setMasterGlide(a_value);
        break;
    case LMS_MASTER_PITCHBEND_AMT:
        setMasterPitchbendAmt(a_value);
        break;
    case LMS_PITCH_ENV_AMT:
        setPitchEnvAmt(a_value);
        break;
    case LMS_PITCH_ENV_TIME:
        setPitchEnvTime(a_value);
        break;            
    case LMS_PROGRAM_CHANGE:
        setProgram(a_value);
        break;            
    case LMS_LFO_FREQ:
        setLFOfreq(a_value);
        break;            
    case LMS_LFO_TYPE:
        setLFOtype(a_value);
        break;            
    case LMS_LFO_AMP:
        setLFOamp(a_value);
        break;            
    case LMS_LFO_PITCH:
        setLFOpitch(a_value);
        break;            
    case LMS_LFO_FILTER:
        setLFOcutoff(a_value);
        break;
    }
}

void SynthGUI::v_control_changed(int a_port, int a_value, bool a_suppress_host_update)
{
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "v_control_changed called.  ";  
    v_print_port_name_to_cerr(a_port);
    cerr << "  value: " << a_value << endl;
#endif
    
    if(a_suppress_host_update)
        m_suppressHostUpdate = true;
       /*Add the controls you created to the control handler*/
    
    switch (a_port) {
    case LMS_ATTACK:
	attackChanged(a_value);
	break;
    case LMS_DECAY:	
	decayChanged(a_value);
	break;
    case LMS_SUSTAIN:
	sustainChanged(a_value);
	break;
    case LMS_RELEASE:
	releaseChanged(a_value);
	break;
    case LMS_TIMBRE:
	timbreChanged(a_value);
	break;
    case LMS_RES:
	resChanged(a_value);
	break;        
    case LMS_DIST:
	distChanged(a_value);
	break;
    case LMS_FILTER_ATTACK:
	filterAttackChanged(a_value);
	break;
    case LMS_FILTER_DECAY:
	filterDecayChanged(a_value);
	break;
    case LMS_FILTER_SUSTAIN:
	filterSustainChanged(a_value);
	break;
    case LMS_FILTER_RELEASE:
	filterReleaseChanged(a_value);
	break;
    case LMS_NOISE_AMP:
        noiseAmpChanged(a_value);
        break;    
    case LMS_DIST_WET:
        distWetChanged(a_value);
        break;
    case LMS_FILTER_ENV_AMT:
        filterEnvAmtChanged(a_value);
        break;    
    case LMS_OSC1_TYPE:
        osc1TypeChanged(a_value);
        break;            
    case LMS_OSC1_PITCH:
        osc1PitchChanged(a_value);
        break;    
    case LMS_OSC1_TUNE:
        osc1TuneChanged(a_value);
        break;    
    case LMS_OSC1_VOLUME:
        osc1VolumeChanged(a_value);
        break;
    case LMS_OSC2_TYPE:
        osc2TypeChanged(a_value);
        break;            
    case LMS_OSC2_PITCH:
        osc2PitchChanged(a_value);
        break;    
    case LMS_OSC2_TUNE:
        osc2TuneChanged(a_value);
        break;    
    case LMS_OSC2_VOLUME:
        osc2VolumeChanged(a_value);
        break;
    case LMS_MASTER_VOLUME:
        masterVolumeChanged(a_value);
        break;
    case LMS_MASTER_UNISON_VOICES:
        masterUnisonVoicesChanged(a_value);
        break;
    case LMS_MASTER_UNISON_SPREAD:
        masterUnisonSpreadChanged(a_value);
        break;
    case LMS_MASTER_GLIDE:
        masterGlideChanged(a_value);
        break;
    case LMS_MASTER_PITCHBEND_AMT:
        masterPitchbendAmtChanged(a_value);
        break;
    case LMS_PITCH_ENV_AMT:
        pitchEnvAmtChanged(a_value);
        break;
    case LMS_PITCH_ENV_TIME:
        pitchEnvTimeChanged(a_value);
        break;
    case LMS_LFO_FREQ:
        LFOfreqChanged(a_value);
        break;
    case LMS_LFO_TYPE:
        LFOtypeChanged(a_value);
        break;
    case LMS_LFO_AMP:
        LFOampChanged(a_value);
        break;
    case LMS_LFO_PITCH:
        LFOpitchChanged(a_value);
        break;
    case LMS_LFO_FILTER:
        LFOcutoffChanged(a_value);
        break;
    case LMS_PROGRAM_CHANGE:
        programChanged(a_value);
        break;
    default:
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Warning: received request to set nonexistent port " << a_port << endl;
#endif
        break;
    }
    
    if(a_suppress_host_update)
        m_suppressHostUpdate = false;
}

/*TODO:  For the forseeable future, this will only be used for getting the values to write back to 
 the presets.tsv file;  It should probably return a string that can be re-interpreted into other values for
 complex controls that could have multiple ints, or string values, etc...*/
int SynthGUI::i_get_control(int a_port)
{
        /*Add the controls you created to the control handler*/
    switch (a_port) {
    case LMS_ATTACK:
        return m_attack->value();
    case LMS_DECAY:
        return m_decay->value();
    case LMS_SUSTAIN:
        return m_sustain->value();
    case LMS_RELEASE:
        return m_release->value();
    case LMS_TIMBRE:
        return m_timbre->value();
    case LMS_RES:
        return m_res->value();        
    case LMS_DIST:
        return m_dist->value();
    case LMS_FILTER_ATTACK:
        return m_filter_attack->value();
    case LMS_FILTER_DECAY:
        return m_filter_decay->value();
    case LMS_FILTER_SUSTAIN:
        return m_filter_sustain->value();
    case LMS_FILTER_RELEASE:
        return m_filter_release->value();
    case LMS_NOISE_AMP:
        return m_noise_amp->value();
    case LMS_DIST_WET:
        return m_dist_wet->value();
    case LMS_FILTER_ENV_AMT:
        return m_filter_env_amt->value();
    case LMS_OSC1_TYPE:
        return m_osc1_type->currentIndex();
    case LMS_OSC1_PITCH:
        return m_osc1_pitch->value();
    case LMS_OSC1_TUNE:
        return m_osc1_tune->value();
    case LMS_OSC1_VOLUME:
        return m_osc1_volume->value();
    case LMS_OSC2_TYPE:
        return m_osc2_type->currentIndex();
    case LMS_OSC2_PITCH:
        return m_osc2_pitch->value();
    case LMS_OSC2_TUNE:
        return m_osc2_tune->value();
    case LMS_OSC2_VOLUME:
        return m_osc2_volume->value();
    case LMS_MASTER_VOLUME:
        return m_master_volume->value();
    case LMS_MASTER_UNISON_VOICES:
        return m_master_unison_voices->value();
    case LMS_MASTER_UNISON_SPREAD:
        return m_master_unison_spread->value();
    case LMS_MASTER_GLIDE:
        return m_master_glide->value();
    case LMS_MASTER_PITCHBEND_AMT:
        return m_master_pitchbend_amt->value();
    case LMS_PITCH_ENV_AMT:
        return m_pitch_env_amt->value();
    case LMS_PITCH_ENV_TIME:
        return m_pitch_env_time->value();
    case LMS_LFO_FREQ:
        return m_lfo_freq->value();
    case LMS_LFO_TYPE:
        return m_lfo_type->currentIndex();
    case LMS_LFO_AMP:
        return m_lfo_amp->value();
    case LMS_LFO_PITCH:
        return m_lfo_pitch->value();
    case LMS_LFO_FILTER:
        return m_lfo_cutoff->value();
    case LMS_PROGRAM_CHANGE:
        return m_program->currentIndex();
    default:
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Warning: received request to get nonexistent port " << a_port << endl;
#endif
        break;
    }
}

void SynthGUI::test_press()
{
    //unsigned char noteon[4] = { 0x00, 0x90, 0x3C, 0x40 };
    unsigned char noteon[4] = { 0x00, 0x90, 0x2A, 0x66 };
    lo_send(m_host, m_midiPath, "m", noteon);
}

void SynthGUI::oscRecv()
{
    if (osc_server) {
	lo_server_recv_noblock(osc_server, 1);
    }
}

void SynthGUI::test_release()
{
    unsigned char noteoff[4] = { 0x00, 0x90, 0x2A, 0x00 };

    lo_send(m_host, m_midiPath, "m", noteoff);
}

void SynthGUI::aboutToQuit()
{
    if (!m_hostRequestedQuit) lo_send(m_host, m_exitingPath, "");
}

SynthGUI::~SynthGUI()
{
    lo_address_free(m_host);
}


void osc_error(int num, const char *msg, const char *path)
{
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Error: liblo server error " << num
	 << " in path \"" << (path ? path : "(null)")
	 << "\": " << msg << endl;
#endif
}

int debug_handler(const char *path, const char *types, lo_arg **argv,
	      int argc, void *data, void *user_data)
{
    int i;
#ifdef LMS_DEBUG_MODE_QT
      cerr << "Warning: unhandled OSC message in GUI:" << endl;
#endif
    

    for (i = 0; i < argc; ++i) {
#ifdef LMS_DEBUG_MODE_QT
	cerr << "arg " << i << ": type '" << types[i] << "': ";
#endif
        lo_arg_pp((lo_type)types[i], argv[i]);
#ifdef LMS_DEBUG_MODE_QT
	cerr << endl;
#endif
    }
#ifdef LMS_DEBUG_MODE_QT
    cerr << "(path is <" << path << ">)" << endl;
#endif
    return 1;
}

int program_handler(const char *path, const char *types, lo_arg **argv,
	       int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    
    int bank = 0;
    int program = 0;

    /*
    if (argc < 2) {
        //GDB_MESSAGE(GDB_OSC, " error: too few arguments to osc_program_handler\n");
        return 1;
    }

    
    bank = argv[0]->i;
    program = argv[1]->i;

    if (bank || program < 0 || program >= 128) {        
        return 0;
    }
    */
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Bank:  " << bank << ", Program:  " << program << endl;
#endif
    gui->setProgram(program);

    return 0;
}

int configure_handler(const char *path, const char *types, lo_arg **argv,
		  int argc, void *data, void *user_data)
{
    return 0;
}

int rate_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    return 0; /* ignore it */
}

int show_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    while (!gui->ready()) sleep(1);
    if (gui->isVisible()) gui->raise();
    else gui->show();
    return 0;
}

int hide_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    gui->hide();
    return 0;
}

int quit_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    gui->setHostRequestedQuit(true);
    qApp->quit();
    return 0;
}

int control_handler(const char *path, const char *types, lo_arg **argv,
		int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);

    if (argc < 2) {
        
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Error: too few arguments to control_handler" << endl;
#endif
	return 1;
    }

    const int port = argv[0]->i;
    const float value = argv[1]->f;

#ifdef LMS_DEBUG_MODE_QT
    cerr << "control_handler called.  port:  " << port << " , value " << value << endl;
#endif

    gui->v_set_control(port, value);  
     
    gui->v_control_changed(port, value, true);

    return 0;
}

int main(int argc, char **argv)
{
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Qt GUI main() called..." << endl;
#endif
    
    QApplication application(argc, argv);

    if (application.argc() != 5) {
#ifdef LMS_DEBUG_MODE_QT
	cerr << "usage: "
	     << application.argv()[0] 
	     << " <osc url>"
	     << " <plugin dllname>"
	     << " <plugin label>"
	     << " <user-friendly id>"
	     << endl;

#endif
	return 2;
    }

#ifdef Q_WS_X11
    XSetErrorHandler(handle_x11_error);
#endif

    char *url = application.argv()[1];

    char *host = lo_url_get_hostname(url);
    char *port = lo_url_get_port(url);
    char *path = lo_url_get_path(url);

    SynthGUI gui(host, port,
		 QByteArray(path) + "/control",
		 QByteArray(path) + "/midi",
		 QByteArray(path) + "/program",
		 QByteArray(path) + "/exiting",
		 0);
 
    QByteArray myControlPath = QByteArray(path) + "/control";
    QByteArray myProgramPath = QByteArray(path) + "/program";
    QByteArray myConfigurePath = QByteArray(path) + "/configure";
    QByteArray myRatePath = QByteArray(path) + "/sample-rate";
    QByteArray myShowPath = QByteArray(path) + "/show";
    QByteArray myHidePath = QByteArray(path) + "/hide";
    QByteArray myQuitPath = QByteArray(path) + "/quit";
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Adding lo server methods" << endl;
#endif
    osc_server = lo_server_new(NULL, osc_error);
    lo_server_add_method(osc_server, myControlPath, "if", control_handler, &gui);
    lo_server_add_method(osc_server, myProgramPath, "ii", program_handler, &gui);
    lo_server_add_method(osc_server, myConfigurePath, "ss", configure_handler, &gui);
    lo_server_add_method(osc_server, myRatePath, "i", rate_handler, &gui);
    lo_server_add_method(osc_server, myShowPath, "", show_handler, &gui);
    lo_server_add_method(osc_server, myHidePath, "", hide_handler, &gui);
    lo_server_add_method(osc_server, myQuitPath, "", quit_handler, &gui);
    lo_server_add_method(osc_server, NULL, NULL, debug_handler, &gui);

    lo_address hostaddr = lo_address_new(host, port);
    lo_send(hostaddr,
	    QByteArray(path) + "/update",
	    "s",
	    (QByteArray(lo_server_get_url(osc_server))+QByteArray(path+1)).data());

    QObject::connect(&application, SIGNAL(aboutToQuit()), &gui, SLOT(aboutToQuit()));

    gui.setReady(true);
    
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Starting GUI now..." << endl;
#endif
    
    return application.exec();
}

