/* -*- c-basic-offset: 4 -*-  vi:set ts=8 sts=4 sw=4: */

/* synth_qt_gui.cpp

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

*/

#include "synth_qt_gui.h"

#include <QApplication>
#include <QPushButton>
#include <QTimer>
#include <iostream>
#include <unistd.h>

#include <QGroupBox>
#include <QPixmap>

#include <stdlib.h>

#include "synth.h"
#include "meta.h"

#ifdef Q_WS_X11
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>
#include <X11/SM/SMlib.h>

static int handle_x11_error(Display *dpy, XErrorEvent *err)
{
    char errstr[256];
    XGetErrorText(dpy, err->error_code, errstr, 256);
    if (err->error_code != BadWindow) {
	std::cerr << "synth_qt_gui: X Error: "
		  << errstr << " " << err->error_code
		  << "\nin major opcode:  " << err->request_code << std::endl;
    }
    return 0;
}
#endif

using std::endl;

lo_server osc_server = 0;

static QTextStream cerr(stderr);


SynthGUI::SynthGUI(const char * host, const char * port,
		   QByteArray controlPath, QByteArray midiPath, QByteArray programPath,
		   QByteArray exitingPath, QWidget *w) :
    QFrame(w),
    m_controlPath(controlPath),
    m_midiPath(midiPath),
    m_programPath(programPath),
    m_exitingPath(exitingPath),
    m_suppressHostUpdate(true),
    m_hostRequestedQuit(false),
    m_ready(false)
{
    m_host = lo_address_new(host, port);
    
    this->setWindowTitle(QString("Ray-V  Powered by LibModSynth."));
    
    /*Set the CSS style that will "cascade" on the other controls.  Other control's styles can be overridden by running their own setStyleSheet method*/
    this->setStyleSheet("QPushButton {background-color: black; border-style: outset; border-width: 2px; border-radius: 10px;border-color: white;font: bold 14px; min-width: 10em; padding: 6px; color:white;}  QAbstractItemView {outline: none;} QComboBox{border:1px solid white;border-radius:3px; padding:1px;background-color:black;color:white} QComboBox::drop-down{color:white;background-color:black;padding:2px;border-radius:2px;} QDial{background-color:rgb(152, 152, 152);} QFrame{background-color:rgb(0,0,0);} QGroupBox {color: white; border: 2px solid gray;  border-radius: 10px;  margin-top: 1ex; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top center; padding: 0 3px;} QMessageBox{color:white;background-color:black;}");
    
    QStringList f_osc_types = QStringList() << "Saw" << "Square" << "Triangle" << "Sine" << "Off";
        
    QStringList f_lfo_types = QStringList() << "Off" << "Sine" << "Triangle";
   
    /*This string is generated by running presets_to_qstring.pl script in the packaging folder on the .tsv file associated with this plugin
    in ~/dssi .  If modifying this plugin by changing the number of parameters to be saved by presets, you should comment this out
    and uncomment the section above it.*/
    QString f_default_presets = QString("empty\nclassic 5th pad\t68\t95\t-8\t153\t90\t-15\t15\t94\t100\t52\t166\t-19\t36\t1\t0\t0\t0\t0\t0\t7\t0\t0\t-14\t5\t42\t1\t18\t38\t0\t0\t0\t0\t0\t0\n303 acid lead\t21\t26\t-9\t45\t70\t0\t36\t12\t29\t1\t99\t-30\t36\t100\t0\t0\t0\t0\t4\t0\t0\t0\t-8\t1\t1\t1\t18\t1\t0\t0\t0\t0\t0\t0\nhoover\t21\t26\t-9\t45\t124\t-16\t15\t12\t29\t1\t99\t-12\t0\t1\t0\t0\t0\t0\t4\t0\t0\t0\t-8\t4\t42\t1\t18\t32\t-12\t0\t0\t0\t0\t0\nbendy saw\t1\t49\t-3\t16\t124\t-16\t15\t100\t100\t1\t162\t-60\t0\t1\t0\t0\t0\t0\t4\t0\t0\t0\t-16\t1\t42\t54\t36\t1\t0\t0\t0\t0\t0\t0\nsupersaw lead\t3\t49\t-3\t16\t124\t-15\t36\t1\t33\t1\t162\t-12\t0\t1\t0\t0\t0\t-6\t4\t0\t0\t0\t-16\t5\t41\t1\t17\t1\t0\t0\t0\t0\t0\t0\n3rd Plucks\t3\t49\t-20\t195\t90\t-9\t36\t1\t9\t1\t73\t-12\t36\t1\t0\t0\t0\t-6\t0\t5\t0\t0\t-16\t5\t50\t1\t17\t1\t0\t0\t0\t0\t0\t0\nsquare lead\t3\t49\t-12\t60\t124\t-9\t36\t1\t21\t1\t73\t-12\t36\t1\t1\t0\t0\t-6\t4\t0\t0\t0\t-16\t4\t50\t1\t17\t1\t0\t0\t0\t0\t0\t0\ntriangle kick drum\t3\t49\t-12\t60\t124\t-9\t36\t1\t21\t1\t73\t-37\t36\t1\t2\t0\t0\t-6\t4\t0\t0\t0\t-5\t4\t50\t1\t17\t8\t-24\t0\t0\t0\t0\t0\nnoise snare\t3\t16\t-30\t14\t124\t-16\t36\t1\t10\t1\t73\t-3\t0\t1\t4\t0\t0\t-6\t4\t0\t0\t0\t-5\t4\t50\t1\t17\t17\t-24\t0\t0\t0\t0\t0\nelectro open hihat\t16\t23\t-30\t14\t101\t-3\t36\t18\t10\t1\t73\t-3\t36\t100\t4\t0\t0\t-6\t4\t0\t0\t0\t-18\t4\t50\t1\t17\t17\t-24\t0\t0\t0\t0\t0\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty\nempty");
        
    LMS_style_info * f_info = new LMS_style_info(64);
    f_info->LMS_set_label_style("QLabel{background-color: white; border: 1px solid black;  border-radius: 6px;}", 60);
    f_info->LMS_set_value_style(QString("color : white; background-color: rgba(0,0,0,0);"), 64);
        
    m_main_layout = new LMS_main_layout(this);
    
    m_program = new LMS_preset_manager(QString(LMS_PLUGIN_NAME), f_default_presets, LMS_PROGRAM_CHANGE, f_info, this);
    connect(m_program->m_program, SIGNAL(currentIndexChanged(int)), this, SLOT(programChanged(int)));
    connect(m_program->m_prog_save, SIGNAL(pressed()), this, SLOT(programSaved()));
    
    m_main_layout->lms_add_widget(m_program->lms_group_box);
    
    QLabel * f_logo_label = new QLabel("", this);    
    f_logo_label->setTextFormat(Qt::RichText);
    /*This string is a base64 encoded .png image I created using Gimp for the logo.  To get the base64 encoded string,
     run it through png_to_base64.pl in the packaging folder*/
    
    QString f_logo_text = "<html><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAAAwCAYAAACWqXFuAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wDHRcgB15yh5IAACAASURBVHjatd13nGRllTfw763Q3dW5e2a6J+fAMIkchgEBJYmCIAomzGkN765h3XVRX93grjmsuuqquyKoiKIgQSTngSENDJNz6OkwnXNX1X3/6Fsz1TUdBvTtz6c+1dV96977PM95zvmd3wk3MMpPFsHwr0EY/S0Y8Xb4HYR5fwgL/ln4ufAn9//RzhGOdrFRvjPacS/nfAr+F45xr+PdZzDGWAuPN8bnseZtvLGN926ca411DROMzRjHFxyT+3eYd64wNsb8BKMtQpj3v+iAWN7xQf4xEy3sRMI2npCGY93oMSzwRN99ucIznlCEYwjreIs80fXDlyH0Xsa9H6vCGG9eRpvOvOPCvL+Fuc9BJJDZPGE66r6zR/4YFAhcEH0vCCOhy//usSyeYx/MKz7eX+l64RhCNJFG8/9hvOHLOP8rud5fcv8F/88JYU7owpBs3ucRgnqUKc1JZvaIVgsiDRdDLIwEMMgTymPdpV7h7jwWEx28AiH6S4UlHMcsHyu8eCVQIXwZmvUvsUCjWZJgAqsUDmu4MPceiVQ2+pwdzTQfpcUKtV5ILBLAeE4IgzzhCyZYs/Bl7MZgAnM60UL7C7XlX0vrvtJzvBwoMBF+HQ+7Ba9gYx3DOfLRWxgJXjY4IoS538McHsz9JAoGn8N3hzVfTvjyhDDI04RHyVGYpyWDI+caVxiDIzjh8E4KxtgxxyrAr3QBj0UbTSQsr0Qgx7v/gnsKCqDR4fnNM4Gihc83iROZ6yAYff2O0nJGvgqHnjVSSeXuIfc5Hy8OC2DeAMIg0nI5IYy0Xjw8IoiHha9gkWLRdxMhRcHwuXMadDwzmo8dsgHpaMekkQmjXTSaIIYTmNjwGLVkMM5x413zWCFH8FfQrnnCF4/WrSgkkVMUubmMtEwmYChkCJloHo8yfXn3nVMwSSRz583D+7lzZ6NzDonWJzgi6DmMFwQFCqpAcIMwb2kSo2iww45ImIf/8m4o3xHJH08CRZmYynhWJVIozV/X4IgzkylYxNzNpfuKpeNZ/ckhvehDXySU6XzPKhiHaijUZi/3J/j/bJ5fjvDmHZOzSMWZmIp4VmVAWTTv8TzFkA6ieQsDnUJdAYPBETxWKNCxSFmk+hMqS9JKDZ+3KE+IcjhuAP2DSV1FQzpD+qN1yQnZYdYkHPm9fI09Qm8lCuc9D+PlBjSqA1KwULFo51TFs6a9+39csGedhZPKHRzoVD24U3W2RjI5U1e83uBATHXmVilDwuQCXcVL9NTW6a7eLrzwKbsWbdM1f5cD6MwG2oNQe0BPyFBuQKNM5suiHV4O7TIRpzYejTLehjgW/s1IeBRPU57Mqn3T572ta6fSoSpzk/QHx8kUzdI+NCDZ1SF12W6PfPpfPBZdo8Pw3BVahZwApjC5JG3Wpf/iKlOlk2XCzDPK0geVJvp1DWRUpQely8+149br3G5oWGFE1ilTAMmCyNTm/IhsOBKSZUd1QsIjGioeRKo+jHZYtAPzecDD8xSZ3bKAaT/4jNP/5iPeZ60pltnpQUWazJHBu71kj3nuUuppKZ043aBvWe836m02yZscsFhb7SHZL3/W2g/82HP9xfaXDGhCZzi8C7OvRCGNQ9aGYcGmCicw0cdynb/CfeWbtVhIScCkf13h8uuW+KyzZbzBFgdN9wOV/sUBz6lxqSH7BOFsfyu0OaQR/QXeaG6tS0ImBcw45QmfeXqFRQ4KParEHdISAj06HGeSRkOmiZ9b7Q/3f9p30RpZqcwopjabZ/7TEaQ67JDkxhobzfTkOyRjkK1BnirMAdZiVN7dY6XvmWGltAq1PuRTlmi2TKM7LPSouCX6nKrLVTqcZL9/VC+tV4O0F9RhSesktR/8kan1e7wrnrEUU0MqgmGckrtmzmHJqftCB2ZcCQ1GwoMRnlz+OfNBd975R71WMLpXOOLeCu5zxPWMHS3IOYbFM6plfFCvh8Tcao4uey3RrFHapdp9ULkHlf38bZahNCAZFKx1pJ0S4fD/J+9YYsXTp+tSqluIJj22KDdLm4xAi6zVsmp0zPmVdGT28wcaFjqjhQYkHCXalii8qWB0q1PoeOR7MjlgXISKLfPV+Y4SSx2UlnCp1a72sB94rTX2WWmf35spLiUQ123AcYqtsccM7Wbrl1UigxYnNM1SVtpr6VCRIfRHOCSd23VGYtYgWsx8uBAWUEcKBMwoHp38741ikoM8zitfeI8yQUZ6ruEoJj8cbVMEeccXaJbYu57R+u5fS5mr30KhclX+wa9wpv9jlit0WyZ7/2aLr+WByLkoXOdY5MhUou6CH7nYLiktBhRJ+6TnrXCcOrvtUuUuU202WD7fof952j3ZQDYIj2jU4IhQHx5TDmeOR9clTADmC+HJGGeKRZ5v2Y4yRT5mn2s02mPAVOv90QLPafCweY43YI2Y/2unbt0q7LTNZHdbZb6ElB5pLYp1u91s7zGQToq946uWXv9pDSEdEcjOhiPh3wjiPA8Ix/I0dj52zPFSOVORT6DmPMMgj56IBSNlJ9/UjKAlcmxCAZ+a2yD51NOIqEG+4I/Ft4Wkgx69Re+xa/AJM3Xbaqo+fbLW2uCDFvmqUlcZ3DDfVMOWKeHI/eQrjdKAmjvPt3zHOeo8YJoHxXXoN9M0ZfrUOegCdZZp1i7znW+5H12xUG/OMZwIDo0XA05MRDEYJTFhlOSEeECJuJL+CpNtUeenOrzdemmlXu2nTvZPuh30pAqrNLjZFJsdp9xxkmqco8NS2/GQhLhB8xRL+ooyH3L2Lz7s+us/bVpAU0hnMIwrcrxk3LCZSUaaOGmYSkhEYwwKFiAbadG0YQ9xINKsQxFmEZ07GVAcHr2AYeRtDmHQEbojZ4pyODoZbcwctTFiQ0eYbCjv2um8c+Q7e4c5tuia/TNDzTtOkFKs1AlavWiRRqc44CUHnOh+xY3TVUcebbJgA8VQnI6pSmRNv/Y2pwY/Vh8+rdjJOl2uSYesu8w0pN5taj1raP61nnz3jV7IBlqD8DD2C8eCcaNZj4J8g6NomJdNU4RH3PjiW04z2UL7DCp1ilYVUjZYY5nve1SL7eb6oJ/pdZlTFZunxy3mm63N3eo1OuhuH3eBJ13gHleZosd0rZZa4ND3/sbSj3zflhzHGGmanANUgfKI/qnITXxvsdKgWtCfkAj7BfFQNt0qiJOujmkLsjrRFdJrWLB7IyEsDobPV5x37nS0eDmB6Q7pCY44R+m8yFHJUFxlMqM00jSpPFI/50EOogv9YaAzCIevnYM4RpqyXGx1CAPH77FxxwVmmqTI1yy2QpMt4rZa6S6P+YE1jX8yHWXRJsiP5SdRlsia9PW/c1LLDqvMlfSQrPVS4g7ZbpGzdLpdpesMeErPzR/2FBpjoY4wonYK9dd42i4cxcImTJClcQzEaBBpnNRdV5tip1KXane/YrU2maMIldZo9BpzdfmQwL0aJNQq9q8O2CKlzSTPqBcodp+VluqVVeRJNa5yAIPV7Q5EXls8unA8Er46zLzx4xbeWmv5xvP1NE3V2Vrm1YPTDfml+YolXOklB82T8px+5aU/V1udMnDJVlv++zv+jD3pmI5EVh9Sf1pg5buv9DepHgNlr7Opd52VyRUODu433VX2nXafF375Vven48JERiaCBQGKsjFVyYz6N97oiqeSVhfP0mOTZLxdb1hGplZVGOjXZeD2L/rP43bYZJg8zuYwZEH0IIzojKGA3pPW6v/jNXp8xgzHa9es1nzPO90y/+5ELzo0sMZUd6gI0oqiOctBglQmpiaRNesf3+m04B5VYcKASXodMGRIi9nm2a/DmWp9XOpVqz154kEbQw6hJ6f9wpEc7zEHCcYioifkwcLRCdIkSp7qtUi5RjvNVWuvKpP9wmSXG1Dvd54Rd7w5N7/DlPN+b1vDEul9PWZf/Z+Snc8LwxO0WO6QpZ6WljRZryslHTTXVFPfdqN1kTbJ4aqigKqWSnOmtPhbv3S8a90Z6xWETS4Lp9vi9xbo0upkTXYqcZtWlVb5g5ref9Hav0zHTxqd8pNvO/HNf+fFX3/LjZmY7nhW8hPfcFFDk/lBmd0GXSKUstNMaYngN2bs+KiFH/uWhqWb9VZ36M3TgKXxrMk3vNU5v3uLy4MBoVb11iuzR79Z+i2QsltJuE7s2k95y5N/458j2DA4DncZRnTG0NVr7f7SLXrFFdkj0K3amxVrdcBK8+1X592euvU36i57SlFO+0barzyRNentn3P+0DZT3Cbr/dq1GzDXDmUmu0mZc5V4VLHJeh74V/egKdL2Q3nE9mjQbMyIUKEpThwrMTqGKQ7yHZBdS2RNtlq3rXYrt8tsJ9kuZsi99gud5hYu/oNtpWlbKjcaWpJ16KZ/t/Kiz5vtUSusdMgsKXM8KtAoa5XJluEEPO2IecoJftU9l5gi1OFanxSqzpY6S79nrVfpoA5LxX3PbHM1mKbZViW+5JBfqc9WSelR7d2Cm74ptf1qFevOdCNitW0qLNAWhqYalLZAvyJZsw2EHWIOmvTr1U759pM2GcaKA2Gk/eJZ9Z/+qouQDYt1mibuvQKBds2K3GNAncAFSk5tszvCrmHBOoSjOCGZgP7jH9fvDJM9IPAenYo1263RH51qmT7TpfSZ0XiWJk8pzYXZkOooN7mq19wbLnRqcFAQftZWg5Je0meVMg+psFq/0CSvErznMY8avsd83i8MjkFpTZQ3GXs5uWIFTkrO/MYjDjDVdsCJ/k61h9V6XI1BxU6xSbNzrHSSHq1l7YKyIc3oTGT1Juh/bIEip3rEW61zhafElQpcivfJeoOYKlz//EpzIqchG12/COUPnWOKIrfKKLbdbEOazdFsigZTxdRqN98Wi7V6CaFe31NtljY9kt5kjwP6/UTN0zud/a1POxc1V2+00wnKpAw5hLk6TdflVC2KJaR0PXKWORHuLA6G76c0nlX9ww96VcN0i92qQo8U1grcIPCkOv3ON9lrBeWnafjeuz2RiQ2bcCM5v1ieV5+b+0yEHbur7tZjqqzZSmxTaYNp1mhxgn6X2OOQ7I+neaMjc1UcUlXVbdIZT3id9crCOyTt1OdF7V4t0K9CuQVCKdtVJc+09Sc/dRdaQroj7Jvz3IMxEhMmDD+OKoDBBDHUMRj+BIrvPMdU5QZ83qBL7XeeXjUadDrJQxapkXG+3uPmazdMKE/GzEPM/+IXbYyts8gfnO4Gi5H0IwP6bMa9YrJ4z5zdUobjj5k87Dlp30xPykrp8R4Jp7vTIv9mjefME0hbrNgbZQ2a65MydpphqS73qjJFxsMS/lHMDAPWyf7bdY5H2ZqbBH4kab+UK3GWHVZp1iZryGDsVhVbXw+qMoGSkFR2eLNM/fwXrUKzWoNu1uM3ThVYZa8V9io1VSdab/yg36EnnjUY8WjxPO/98CvMSxKIhLBv1m49PqDVjercYbpSFWZp84JBs8R1yLRcpT9yylIoHywy+aXVFq1tMdsV+p0rJibtFHP0KjNdsbslnaDP923++nXW4iDa0JeXZDqu2ITGz1APxjPBxxLID0cGsot+NWiFs7X7pVr1yr3fH20RqjDFVbZqdbUaj0560VX3LLdk8wrTG06w8V8/aY47nZQt12CTIZ+21npJiySlwH4vWXxhpx9Ud1gYDicnZKLrJwOKbrvM/QZdrdL3VDpZtdeqN+Sn5jlbh+9IeFqFT9pug1m+YJcG5abrUm/INh2WqTBbn+kqm5PC3gplJ+zU5FWabFbjST2GVNhhoZP0OV13WCHV1WlJ62S1pV3KSwaE8azaH7/PyU31prjeLGc5YBqS+q0z1SZV1ipXJ3tcvYHX32ZbhKmKAirCI/ykMUxcLBp35rh59r/YJXSremdptkiflINWq7bRYjMNNE5RHglgeSamrHhQ/YU/dGlQrij8mWoLtRlQ5UlZ79TvKXHXGnKJO6bf4ZSP3eKJkBbD3n46L8k0eCUJHeN6wUxcxFJwXCwXAdnzFXt91Gu9xWZX6dJiu7gT3W+S+arF1Uq68e5PaL77w6YrtVmnN/i1akXi+hT5iV96Wspu1V7jAB6RNcnxvvHVFU7A3hxNEgH2oKtcLy5TZKob/btXaTPDFqc7pF5s4XPmVaeVeqPGZ75gbvYq231TndMNOl+3UK9zNDvNkOkme6eNtjnlkTM8e+Gf7Vv9or2PPajOGhX2GbJMr+t1+YJM+CWzfN7uTQvVrXxBZWZIUTyr7jNfcJasSm/TZsCQlFb3mq5BVqDM+w2p1P/AMndHc1kREcb5Yb5EnknOyWMmomESKDrtf3Xf/A7tzjOgTLsK7ZbJuF+5ZVqkTOmNqUMVasKs4tvPtXD/HPW+arLL7dMplHBIqNFGpSab6u89KjT/5q+4Hc1odyQG/4oTdMPxvODwGALuwdGZ0zmytmzTVHN92606JbV4UGC6pyz2iJX+07MeN80sSz1khm0qvFeZpAe81Xz7NJlpqVtMs9JaZU5Rab/1fmal36152MKVL9oVcig4AoITCHvKFEXm5Veu0XTF1xz/8XuUnLDWknivTHe1vt7JOvsPKZlX5unv3mHyP9xso89a43699kmYo9QV9qu2DUtl7e4vN4iBSzZoemyRwPeUW6jYIi/6vEP2WOmdOlF0x3nmrX7CVqS/+QmvaptpEgZ1aVch7S41TjBknphKWS9KvHmtXfW92r58uTMfOtvU1CIDxf16soMSAxVqZu2xrrPSlDAp6ClRV97lQCYpaK1R9YZbPPWBH+u7skHT3x90gpkG1dljsoxbLLPCkEZ1FhqU1vnQalPPeUxPgtRVX3GllH0uUORpKado9IJB9VgmNFkfOl99h/4zH7QhpCWgNzxCOod5Ic5jUnzj0XsJ49jpcGzVeTgCEu3c0oMPOE6Vdo32S3m/K3zcbBdZY5dunebabY8i57hFuRX22a9KhQ7N6u13i7ku1KvVlRZ4xI3+yWXuPf9uv7/3IvOygb1BeJgCCCJcVDS1UWb7XDP/eK6zUlnBAymdV3/OS01nexgXYYUvmm6pDn8wxeWaPGySqba4RkapPqVatNnvu670PkN+pTjsBz2vfsy+z92gxRrlHpVwjZTbLHCutKxi+ww+cJZ61CP2hWudFvxOMjxHt8m6dJpkriLlepVIqNbtZMGvz7N2/3SVn/29Mw2YJi3QKm2WXmw1zG0u8CczzTPVAs06VCvRd+clWt52g90LXtJjqhKX6RE3yS4zvMpLBqUk7RZT6hbT7j7LonMe0/+jD6noP1XWDeZ4i5f82YnKTXIqGDBZm12mma/iD6/3BJoDOh0hnUcgg2NNRxpPA8ZMwOGMBh7DI4HneEDx/dNMt0DWawyYarHj3Od7vmyZW5ygU9YOA5401aDAg9isW7GfmyyJ9aabb64y+8yy181Wxd/qnz/2M7F7L3JSyL4g1BIM478wEvrKyJGZctuFwv/zP+76wGe9cOMP/bjpbHt92A88YLlPmewa22V1eJODQuVqVWk2zwZZT0vb7XZNZlttn1YJH9E+d5MOdJ/5pAOaldgp7XP2C/R5vc0m6VSuz0Nqn11jJmZ+42+c07VKeXiGmMkGDGjyJ73uEXeTpA1qEX71ix5H162XmYEKgV6lNplln17PYA+a3W+uSpMUa9Yj1KzRM8r1eE1HlTKEc3d6Xtxv9Cg3x3Y1ytVrMUenAUVWKFp7yDTM++A3natdk3Jl/tly/+RWdZrcbLql9tmiTp3+f3mbx8pCu0Naw2HHI/MyM8wmVIvhWCY4GCPBszDxMzxCapb88Tx1Am2eN0OPTQ6Y4/O+r0eJmda63+W6dDvgYu/TIaHKE6b5iAN6NJghpd7TupT7totcZ0esX+V3Pm5TNtAUC7VF7Hs6imtWBkxvT5hds0HMYltwroQVPutis+z3DXd52CRfc58HnWiKavS6X48ie/2jFg9a7lz3eczb1CoyoMQhg8p0rNqp0TDtEKzY45kXljrF9832fhuFpqFNSpu3WtLLdiy+7mvKYx2C7C4p16uxQtbF2rxoskBaiaG6uwx86uvWIXzodHWoELdDIC10j1Jxw1kmKefZq0/GdnFxB2y0RFogpnd6wzAWnrPB5F0xs5SoUSaG/8JBnV4nYVWwX6rrYtm/TThFibSMci16zdDvCbMt9JgTHW+tJabpTmRt+qcbtUQ5hF1Ran+Yl5f4sk3weFY19golOZdik0TqyTcq94w5ZlgrpkaNg/Y4TcLzfu0DmsVcabbpalQ7YI4u0yzwLhd62EmmqhV4zPUWuM463DZUouGqrzsuFh4p7wuHQ2+lAVNeXGpFzZD56lxhl495Upci251rswvs1atchS3e4+1e0C2w2xwd3iqj3RxZ5Yrc6m7TLfGAx8Sc4pA+yckx/VGctxs9V2+wWbkBH9QiKS006Dn1utXYpdUOk/75S4b6Up7IVjlokm5LkValxywzJDyiTie/fYc/RpTG4LqV+vQ7aLOpmu0Q2BdtsrkyztWqTcwuyz0u1OYNDigTW7ZeZ7Q5upY8o9Mc21Rr02G/Hc5zwKV2Odv9hK/z+PpXa/n2D+2VUa5MzCkGnGmfaYqEVkppcJxD2jT8x3X6sS9HuxiZxKrABOdXUAYT1eMYjwcMjrEmIq9rQjwc9oBreue71yc9aKPTvcNe+52mRIlnXeMyt9lltoTbxXQ65ATVnvVT1S5Q5DU6tSh1l/Odp0KD27HFVlf+9hNuaa00LSQVJVUWRZTC9Nf8yGL7LBG3V43brHLAbB2O0+JWy3zPdHda42P2WOEUCyyyxwqbLZUx1S7rzXempZo94EJn6dGo1EleXPmUnYa97Z5soPukhw1Yql0cQzIO6DfZkHJp09Qql/j8J9QEPcoMWWSbXotsdJmtquxTqcuntJy+1641LdaHwynymW0nmSwrYYm7TLEds/zZcrss9IyULjMVK0K9Tov0KHOJ+y98zIbIInS/aoNdDjhTxiH9Dtktabd6++3wtA6PW9L3gPlaLLPXQTxplV9K2mGx53WZa79LVft5fbG5n/iuh8PhkFt3LuU+GCMgFowD34JjVGaJsYLHxihLzEtMzTkgyWdWutAtznGFB/Fn7/Jf+pxildn2KHKFF+PXueSJx/zpuXtVh4HeD3zDWl0WGDLkIa91pW86ZLdJ7vWo71iswY0+8sf3uf3ab6gMaQ+GaYiae85X2bjGd/T4kZRvC9X5tTXO1aDLLKsNCtRKi4spcbvAVjO8yiFv0iXhkFLv8t/6haZYo1GVCrNs9axlxz9pT7TAfUEodskD9klqlhbImKZG6Dmd7lTrJL2eVed99oehuQJ7zdDrcTFtysxWZ6YdqH3iXX5l2JMffOYk07BCnxelTVdqrl+Z4q2SYrrNxgH9OtQo1adBkYUqZM067SnPRHmR2Tf/1t63/doL2CDjbP1q7LRTm2pFBmXt9gsLPCxttXJzoijHYgM6LDbLFtW69froY1e6OTMMeTryaZeXU+56LEkIo8aCg2OoUy0wwXGUdJYq0iL0BrfZZqmFVljvXDHbLZIy2w+kfO68Q35/yn+oPeVhTTh72wI7v/IZGzQ435VuknGTSabb5pvOEvNdJ/uYtb/dYN+1TIlCQdmAmh++WxYrrZd2phkedqI3uscWp1pho4+4Rrmeqst1nn+DttO2aJ3VpuqhR0z90ZW2uM5FjtNsuT1aNTtNoFup37nElbZc9Hn7I/PTH224Q7P3ye4p0qbOIR2alVtplg4nSWlR4iXTPC/mLXY5QYmDZlqOtIRWqY9+z3ppuyNaI5y3QwO+YZKFWKrNNCeoENMlKykubZasPlkZGWd6QYtBM0w77x47A9pCYomM3uSAZ4eKTTagziw7zbBBt4wOk3SYIaneUzhOm92y5nrSBm+x1RylMqbZ+apWW+ZvciC6v55cWlh+dnZQwKiMIjNBeKyAcIyipFheLXCuICkRpT3l4pGxiAKpCpj3tfc679NfsVTMw6rdp8s1unC7C12sWY8Oex33llaP3niNR9GUjitNZMwKup2jzHSh/8YBG1xjuT1esMIKjVrdrNYZYaANG6M45Oyy7/p47/vdYZ03mGmbNru0KPEa7a73Zq+x98RnNT1zqTT2R3TRrBkPK24IrQ6n2KtfxizbPK7SkJm2KFGtxhkawxP8GM+FNAaUYP6Hvu+qH37YEo+r1KDPpdY5oNhcceucpktCk8A1btFnjV1KPKTMJKXFF9naX+l/QzYFNEdgvvb5lRbed776KS001JuRrlAUDgrSCcnkoIHBpFT9fvuHiiU7upQGix169w9smd5gb5SUW4zFy5/wug1xCw1IWWDncPKaHtMU+4GTvUPC7/WZb8BrrRVX44Aq++0x3QrzbO+c4oniPs8VDQ2fO8rsyY5Gt0zQUCnXoiObV+edK0rKxbuzuazdxMtJxSrAjkmU3HWGGTaapMgncY7J7jRP3CL3aVRuiSccp/l1b7M/yqZoSmSUYMob/+R3v73SZjGPGfRDy633B6uco8GQO2zxPmc4+MfXir/uDhWRVirv/aj7DTjZDk1SZnpRkwvt9hnH+YRN/mzJ3N+rxIsRSV19xc/tOlDrfH9ySIeZptlhsc1WW+JBBKZpFZTX6Yyq7/qjqEMwlND32tvs++GHHa/VFPNsEuoRmuQzVtuuRIlWH7Zep3tVmqzIHKeqdZKm66/2EBoMa62eaPEyq9brW7XejgjKPDvGGsfzKswGoznITwroXbxZesMVetyr32MWatZjin7n2OUkgWKDFmvwJk8ZcEiRWeZqsM/Vih362D9prOi0C4dCeoMj5Q4jOlMcixccHGM564Qp+RNozVgu82NzhYXB6XaGj0oJpfU53jwP2ulSS3WocAm+fv49zsllEEfE5v7/fYfy316pVtYXBW6X0epyj2O/Tt+UtgI//a+pTnvdMNUxfIu7zFSvwjt8B290khtt8C5f0u2LzrJV9S1bVS/5gKI5b/HC7tfwOQAADQVJREFUn8+12UOu9At1TtbiHA97WI0GJZ4zaIcpFuhziZ7jfm0gWuTBKDN6KJ7Rc+F9DnhBpTRazbZV2ku6lTvgnw1ZJ21QTLvLBWarVSvQsvoJv3jTTZrD4ZBWdyTUYTAsUP1oz6s/GbMXS15CajoqRwiiNLjepY8avKVIvdNsV6bfdL12a7Bdt15bNUhartvj6i22TI1N4uY53574gO3f+Zpn03FN8YyuSLDzEw4KNeC4RHQ4AY88bkr+eMmnBROTq4KrbHyd7rDTdJUO2G6aPaps0ut0j5trtXstTyxw7tQm7VEiwSAy6biOeMYclAnsMOBrit2AP2vwTuU2W+MJWTV3fNMOPzU5AsahA6ql1EoIvKTOCueZ4QmdpviErZ5xkrWKtuw2a8t9+n3Bax3CNbo1iUlqM0m/R8y3XLPl1lqi1l3mndxlb04AIwJWLNRXMqC5dptDrS2qbEKbemUCJ3hKmRL9TnSKJnvMN9seoSpV/PB8pdgfDHu+gwUhrXRwBNYclUEyyqKGeen6sVxNyiVb7fy3bzvDI3rda7Fd+lyg1SL7rHS7lEE7VNrmVHv0OcVrLdCMvhuvsR6HEhltUaZRNi/n8qjmVWO9B8dWvjF2JGSshK7gaA84V/NQPBhXPFTmtypsMc9mZzsgLiO0xAI1bhKK6z17rb6I1BwIhzHBYCKjp2RA/8V32IK1ir0Nv5E2X0attGptzhYzL6xk/8zDvGN6ecoGHVJi5pqhRZNZsuY5YJ5nJC3X5AytPu4B5eZ7s33eYb/nJHWp8u8u9WsLTUadpMBkj5rjLJ2rnx1emOAIBkpHgj/w5maPer9npCT1qEa1jZaj3UWe9agqMfOEqgVq3nCbF5fvtiGMTFteFZlIA2bDSKs5otnSeQVTI/4WRr1ygiPdpjIYWHO/ViXanKfSKoPeJ3S8YgfNs1edn7oAU73GFmeotsAu7Xqnrrfzzb+3JxM7TLqn80NuwSi5VqM1jgwmyHoZL4QSz/3yf0cSzEFBMmR+ieLhCv2fvd1xt52qXtqgSe7SZY8T7bXaQXsl1cs63Z/PfUb9G35ve5RZ0Rup93hIau4u0372XgsMeAxnStgv4RGB/ao0+gcXW6Ik1ia4cO0wvC7tlvzD+z0jNFO5m5RbJCMtba4Wg2J6zPWin1lmnlaNqlyrzyo91ogZMqDXfFvUOVXMR610jVb1tl//di8UDdkbZYAMRmNODsZVDuy38OYTnWObCtfY4XS7LdYkoVZMiU0mW64PL0qav3GpX2Vi9sTCw0KdzSukDwq6gh0Th1aAx+LRWtR8620WDARSTvOwOcrN1GyqOaqkJEwXKvddZ2sx0+NmONcju5d7OtlvTyKrMb/OIw/LhQWRsfxuGOFoHbYK+/3kNkt+s8rcuL84Vix4PNWZV7yeuWG/k33BR9zrEgNe70GXmqRXpy6LPGKZl/Cbv/269Ya1Xy6onQkZCANtq56XEvhB0QtSEgbsc4FdvqzP8djm791klod/96bhCQrpetcNGsp3WCNuFY7HbEX+0VyPudhNVnnAzV4vY5IbLNeg1jfM9Yg6Dym2ValPeNTXHDDFoDs9p9Pc2AELy3u05Jmiw1MRD2XO2e+QpXZ6s5e8pM8eKVXSdmpWKrBCXIkSKSd96R/cgcZYdti0BSNNm9HMXF6epXCCdsqRJGRzlXULthvCPNTptMGQ7SYLJEwzzV5JJ7tG1nTdPmbL6of117boSmS1OlIJeNj5CCfI43sl8eDw5dQFG7s+JGet+/auViLQ6jG1bnOx15npA65yri3O9gez7MX/mbfLc4aJ0yFHqr6GhLorejSWveRHg5P8UaezJG1XI+sFr7PGAo9ZabupO97uj5EWacsGBrsW+F1Vu5M7qwzodIpyPxIT06hYkcU+7kXPKvcuHTZLJkLd6bvM0iNmv6x1VmiXdZFiWb+3SuXCzfZFmm8o1wYjyssrCUIlUw8qLsp4YLDJWQJxgZgBCd1WqtBtnTkydlTOtelzX/FcpPG7omq3XDuOiTrEjRdQCPKFN69jVefyRpufuc7F3uhkZwoUe9xGk4Q2q1NqqmekTAkGtIVx+3/9Frt7U/al+rRHuDyb381hgtqicVOvxqor+ovrgvOa5QwFDPzdd/3pU5dZotxg8FFh8Jx14SIV6gwGWccP/sKbz4p7uLLTvnBkh6Zs9HsXWh94jwcvuFNdyUaP95Q6N2xUFjbo9T/qddg7+HqP/92PNRjOzG2PhTqHEoY6qoWblmhdtcGXB2OWGHDIFCfabLpDqiUNLt/mmd99ycaSJmVLnzXX9Sb5tsbwYYvC46UESsJuF4cbJb/4BQ9FWCgWJTwkUJIN1MRCU7/8BssG3+s8H7ffHiUm2WarhE1SMipcpVmPF19aZV020BiEWiNPNxOMAonyevCEwTH0KgqODjRkI7qo9VPftuGOb7mzO6k8frfGsNPi2EWeyNzn/NgFng/3qYhVWRt2avv7H2ufud8Gw0X+ffKwaUEXjMJeNcFE+YDhOEGN8YrfcvYmltcTOkdCJ/JrSnNVcCHlsZhqWaWG+4uU5PUgyZmvdvSk4zoSGR1htBiOtK4ojgq+J6M6es/dX671V64h4qFsoDUW6omOKc0M11/Ux7OqWyYpGioRHqxT3l6qdFqXvhkb9FVkdAzFDSUzh9tg57onpPMwT1q0QbKBdCwUj7KIq6LYc83PPmTZe35gsX8zzxyBWwxql3KxbWoUe43QVI+c/Eupde/2EF6KMkr6gjxslec1jujINVaJ4ziUTK7IPFeYXxPdb6XhvozZaKwD0XvOoepDRzicbNAZ5K3JKPd2zB3I8r+TV0Q/ojtWmEdEK2g1kZ9kkPNyc8UwcUfateVqEmJRu4liwyA4mSek+U51zoPsz1EQwdHtwZKRIJbktZDINzVhrh1F9Ern1SMXIxWSysSlkMjExbOBMBZKxzIGkxkD4RHuLR6NLRhFk2SjcVXdcK2TPvAB74z1qhAa6k4p9aSq4ALN4TzVtjjoeRVO1Og+syzBk2LOt2/95W5f0uORZMaeKJlzKK+5UH7XscKWcKGXJ4D5TYYSeWtRlDdGBUIVRuZ2MGQgR4nl16DkFcIHo5jkifJOR7QRkSeAeRs+55QcHQkp5JwKNWceE56r0M9EgD3fezZKNX+moB1ZkNccKIx2R19enXE+0MjtppyQ5BYyk6MhAroTGbGQeDxzeOJy3zlcwxqOzGUsXNBEpO0qf/kOJb1ZU6ww6HmVTjHgv6XCV6t0vyE/UeY0e8RM80m7NehygXkf+a5nV3RaH0GF3mjnH3O7uPFA3yj12PKaKeXWYiA/TWoU6uRw1/pg5PyHwdHnHjMnYKzu/+NkY43w9sMxakJGc3wPt94v6NoU5g0mM0569lG8ZUFbt8Mt/HPnGWPCw8JdFgl9jktLG9kKLb9LlVGw1GjMfBBBjtRTO11rn1qT7Hay9VI6fUelKjMskrbJJDWmu02FF9V6ta7amA3/+WkPRtivM2qLO64zWWDqRmzyvM0+GgYcLWEpm+fgjSfAI1q+jdVSY5RWduOG4oKC3s9GPrIhzPs8uhccHG0C8p90k3+yQo84CMbvkDQipDNGr5rxygYUxCRH45qCCZymQh6r0MzlWrglUda0WIsWs+wxaJslTlKkQbslWlTqcpFqDDnbkKQiFdYdmumBwaSmouES9r6woHvAaEojHEXRBCM3yVEUTTC6N5wTwAmbsxYKVaEgj+LiBgUZ8oWhuBEF6uHIyr5sWMD9Fa51bAwwmf+Um6yRT7zJv9HCyvjRXoGxAW1hu9+jXuGRjRAUDv7oMpVRX4WTHBZsrhEx7j0zlEqb6v1eskeP1Zo8JWWHOT7nTKzSp05SqF3cAtc3LXWPIfuKhoYjCuHI7gHCv84jTCay2kE4yvjC8dfkr3FfQWHX15z85D+kpmC+wxGhuDEemRDmPSIhmy+I4dEnDF5BUux4/NJRr/HCOuHYkaLR0s5GnfxozOkXlsnap8hvLHa26QYsdNCgS7UrjRpBLnHAzy2cvteehvlaprQ6iH3hcGLBQPAXPDvnWMJXE8zhuK/wGB8udIxEdE4WCvvZ5GQl/xEbuePCo+qCRzOZec5G4c0XtuMKjiFeXdhocSzPabRxBuOY48IDwgmSdUetr4qun0H/pXfbkzpDY99sQx43aL4hu80zZNA04ZQntZ/eY/17n/abN/yHjVGKWXNE4wwUYLHRsNy4GPAYecBwFHw8quN8LE7NRHtiHBgRBCMfiJMTvExB59l8IRwRxjvqYYXByHBbzJFk1MOJqXlcYRCMfGzXqA9bDMehHfKA97gZYcfwjLVRrzkGKV8oDLlxprKBmnioArURn5Ys4AvTER3UFQ4nWHTnpW/lYp5BfvuK8Ogxj8CAE419nEhVGI7dNnnCeRtjg461fkclnuaHBIOjO+Nn8hNQC9ofH8Z+/w+KUyMGibcvugAAAABJRU5ErkJggg==\"/></html>";
    f_logo_label->setText(f_logo_text);
    f_logo_label->setMinimumSize(90, 30);   
    f_logo_label->show();
    m_main_layout->lms_add_widget(f_logo_label);
    
    QPushButton *testButton = new QPushButton("Test Note", this);
    connect(testButton, SIGNAL(pressed()), this, SLOT(test_press()));
    connect(testButton, SIGNAL(released()), this, SLOT(test_release()));    
        
    m_main_layout->lms_add_widget(testButton);
     
    m_main_layout->lms_add_layout();
    
    m_osc1 = new LMS_oscillator_widget(f_info, this, QString("Oscillator 1") , LMS_OSC1_PITCH, LMS_OSC1_TUNE, LMS_OSC1_VOLUME, LMS_OSC1_TYPE, f_osc_types);
    
    m_main_layout->lms_add_widget(m_osc1->lms_groupbox->lms_groupbox);
    
    connect(m_osc1->lms_pitch_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc1PitchChanged(int)));
    connect(m_osc1->lms_fine_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc1TuneChanged(int)));        
    connect(m_osc1->lms_vol_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc1VolumeChanged(int)));        
    connect(m_osc1->lms_osc_type_box->lms_combobox, SIGNAL(currentIndexChanged(int)), this, SLOT(osc1TypeChanged(int)));

    m_adsr_amp = new LMS_adsr_widget(this, f_info, TRUE, LMS_ATTACK, LMS_DECAY, LMS_SUSTAIN, LMS_RELEASE, QString("ADSR Amp"));
    
    m_main_layout->lms_add_widget(m_adsr_amp->lms_groupbox_adsr->lms_groupbox);
    
    connect(m_adsr_amp->lms_attack->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(attackChanged(int)));    
    connect(m_adsr_amp->lms_decay->lms_knob,   SIGNAL(valueChanged(int)), this, SLOT(decayChanged(int)));        
    connect(m_adsr_amp->lms_sustain->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(sustainChanged(int)));        
    connect(m_adsr_amp->lms_release->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(releaseChanged(int)));    
    
    m_groupbox_distortion = new LMS_group_box(this, QString("Distortion"), f_info);
    m_main_layout->lms_add_widget(m_groupbox_distortion->lms_groupbox);
    
    m_dist = new LMS_knob_regular(QString("Gain"), -6, 36, 1, 12, QString("12"), m_groupbox_distortion->lms_groupbox, f_info, lms_kc_integer, LMS_DIST);
    m_groupbox_distortion->lms_add_h(m_dist);
    connect(m_dist->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(distChanged(int)));
    
    m_dist_wet = new LMS_knob_regular(QString("Wet"), 0, 100, 1, 0, QString(""), m_groupbox_distortion->lms_groupbox, f_info, lms_kc_none, LMS_DIST_WET);
    m_groupbox_distortion->lms_add_h(m_dist_wet);
    connect(m_dist_wet->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(distWetChanged(int)));
    
    m_groupbox_noise = new LMS_group_box(this, QString("Noise"), f_info);
    m_main_layout->lms_add_widget(m_groupbox_noise->lms_groupbox);
        
    m_noise_amp = new LMS_knob_regular(QString("Vol"), -60, 0, 1, 30, QString(""), m_groupbox_noise->lms_groupbox, f_info, lms_kc_integer, LMS_NOISE_AMP);
    m_groupbox_noise->lms_add_h(m_noise_amp);
    connect(m_noise_amp->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(noiseAmpChanged(int)));
    
    m_main_layout->lms_add_layout();    
    
    m_osc2 = new LMS_oscillator_widget(f_info, this, QString("Oscillator 2"), LMS_OSC2_PITCH, LMS_OSC2_TUNE, LMS_OSC2_VOLUME, LMS_OSC2_TYPE, f_osc_types);    
    
    m_main_layout->lms_add_widget(m_osc2->lms_groupbox->lms_groupbox);
    connect(m_osc2->lms_pitch_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc2PitchChanged(int)));
    connect(m_osc2->lms_fine_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc2TuneChanged(int)));
    connect(m_osc2->lms_vol_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(osc2VolumeChanged(int)));    
    connect(m_osc2->lms_osc_type_box->lms_combobox, SIGNAL(currentIndexChanged(int)), this, SLOT(osc2TypeChanged(int)));
    
    m_adsr_filter = new LMS_adsr_widget(this, f_info, FALSE, LMS_FILTER_ATTACK, LMS_FILTER_DECAY, LMS_FILTER_SUSTAIN, LMS_FILTER_RELEASE, QString("ADSR Filter"));
    
    m_main_layout->lms_add_widget(m_adsr_filter->lms_groupbox_adsr->lms_groupbox);
    
    connect(m_adsr_filter->lms_attack->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(filterAttackChanged(int)));
    connect(m_adsr_filter->lms_decay->lms_knob,   SIGNAL(valueChanged(int)), this, SLOT(filterDecayChanged(int))); 
    connect(m_adsr_filter->lms_sustain->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(filterSustainChanged(int)));
    connect(m_adsr_filter->lms_release->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(filterReleaseChanged(int)));
        
    m_filter = new LMS_filter_widget(this, f_info, LMS_TIMBRE, LMS_RES, -1, FALSE);
        
    m_main_layout->lms_add_widget(m_filter->lms_groupbox->lms_groupbox);
    
    connect(m_filter->lms_cutoff_knob->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(timbreChanged(int)));
    connect(m_filter->lms_res_knob->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(resChanged(int)));
        
    m_filter_env_amt  = new LMS_knob_regular(QString("Env Amt"), -36, 36, 1, 0, QString("0"), m_filter->lms_groupbox->lms_groupbox, f_info, lms_kc_integer, LMS_FILTER_ENV_AMT);
    m_filter->lms_groupbox->lms_add_h(m_filter_env_amt);
    connect(m_filter_env_amt->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(filterEnvAmtChanged(int)));
    
    m_main_layout->lms_add_layout();
    
    m_master = new LMS_master_widget(this, f_info, LMS_MASTER_VOLUME, LMS_MASTER_UNISON_VOICES, 
            LMS_MASTER_UNISON_SPREAD, LMS_MASTER_GLIDE, LMS_MASTER_PITCHBEND_AMT, QString("Master"));
    m_main_layout->lms_add_widget(m_master->lms_groupbox->lms_groupbox);    
    
    connect(m_master->lms_master_volume->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(masterVolumeChanged(int)));    
    connect(m_master->lms_master_unison_voices->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT( masterUnisonVoicesChanged(int)));    
    connect(m_master->lms_master_unison_spread->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(masterUnisonSpreadChanged(int)));
    connect(m_master->lms_master_glide->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(masterGlideChanged(int)));    
    connect(m_master->lms_master_pitchbend_amt->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(masterPitchbendAmtChanged(int)));
    
    m_pitch_env = new LMS_ramp_env(this, f_info, LMS_PITCH_ENV_TIME, LMS_PITCH_ENV_AMT, -1, FALSE, QString("Pitch Env"), TRUE);
    m_main_layout->lms_add_widget(m_pitch_env->lms_groupbox->lms_groupbox);
    
    connect(m_pitch_env->lms_amt_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(pitchEnvAmtChanged(int)));
    connect(m_pitch_env->lms_time_knob->lms_knob, SIGNAL(valueChanged(int)), this, SLOT(pitchEnvTimeChanged(int)));
    
    m_lfo = new LMS_lfo_widget(this, f_info, LMS_LFO_FREQ, LMS_LFO_TYPE, f_lfo_types, QString("LFO"));
    m_main_layout->lms_add_widget(m_lfo->lms_groupbox->lms_groupbox);
            
    connect(m_lfo->lms_freq_knob->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(LFOfreqChanged(int)));
    connect(m_lfo->lms_type_combobox->lms_combobox, SIGNAL(currentIndexChanged(int)), this, SLOT(LFOtypeChanged(int)));
    
    m_lfo_amp  = new LMS_knob_regular(QString("Amp"), -24, 24, 1, 0, QString("0"), m_lfo->lms_groupbox->lms_groupbox, f_info, lms_kc_integer, LMS_LFO_AMP);
    m_lfo->lms_groupbox->lms_add_h(m_lfo_amp);
    connect(m_lfo_amp->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(LFOampChanged(int)));
    
    m_lfo_pitch = new LMS_knob_regular(QString("Pitch"), -36, 36, 1, 0, QString("0"), m_lfo->lms_groupbox->lms_groupbox, f_info, lms_kc_integer, LMS_LFO_PITCH);
    m_lfo->lms_groupbox->lms_add_h(m_lfo_pitch);
    connect(m_lfo_pitch->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(LFOpitchChanged(int)));
    
    m_lfo_cutoff  = new LMS_knob_regular(QString("Filter"), -48, 48, 1, 0, QString("0"), m_lfo->lms_groupbox->lms_groupbox, f_info, lms_kc_integer, LMS_LFO_FILTER);
    m_lfo->lms_groupbox->lms_add_h(m_lfo_cutoff);
    connect(m_lfo_cutoff->lms_knob,  SIGNAL(valueChanged(int)), this, SLOT(LFOcutoffChanged(int)));    
    
    /*Add the knobs to the preset module*/
    
    m_program->lms_add_control(m_adsr_amp->lms_attack);
    m_program->lms_add_control(m_adsr_amp->lms_decay);
    m_program->lms_add_control(m_adsr_amp->lms_sustain);
    m_program->lms_add_control(m_adsr_amp->lms_release);    
    m_program->lms_add_control(m_filter->lms_cutoff_knob);
    m_program->lms_add_control(m_filter->lms_res_knob);
    m_program->lms_add_control(m_dist);        
    m_program->lms_add_control(m_adsr_filter->lms_attack);
    m_program->lms_add_control(m_adsr_filter->lms_decay);
    m_program->lms_add_control(m_adsr_filter->lms_sustain);
    m_program->lms_add_control(m_adsr_filter->lms_release);    
    m_program->lms_add_control(m_noise_amp);
    m_program->lms_add_control(m_filter_env_amt);
    m_program->lms_add_control(m_dist_wet);    
    m_program->lms_add_control(m_osc1->lms_osc_type_box);
    m_program->lms_add_control(m_osc1->lms_pitch_knob);
    m_program->lms_add_control(m_osc1->lms_fine_knob);
    m_program->lms_add_control(m_osc1->lms_vol_knob);    
    m_program->lms_add_control(m_osc2->lms_osc_type_box);
    m_program->lms_add_control(m_osc2->lms_pitch_knob);
    m_program->lms_add_control(m_osc2->lms_fine_knob);
    m_program->lms_add_control(m_osc2->lms_vol_knob);    
    m_program->lms_add_control(m_master->lms_master_volume);
    m_program->lms_add_control(m_master->lms_master_unison_voices);
    m_program->lms_add_control(m_master->lms_master_unison_spread);
    m_program->lms_add_control(m_master->lms_master_glide);
    m_program->lms_add_control(m_master->lms_master_pitchbend_amt);
    m_program->lms_add_control(m_pitch_env->lms_time_knob);
    m_program->lms_add_control(m_pitch_env->lms_amt_knob);
    m_program->lms_add_control(m_lfo->lms_freq_knob);
    m_program->lms_add_control(m_lfo->lms_type_combobox);
    m_program->lms_add_control(m_lfo_amp);
    m_program->lms_add_control(m_lfo_pitch);
    m_program->lms_add_control(m_lfo_cutoff);
    
    
    /*DO NOT remove the code below this line*/
    
    QTimer *myTimer = new QTimer(this);
    connect(myTimer, SIGNAL(timeout()), this, SLOT(oscRecv()));
    myTimer->setSingleShot(false);
    myTimer->start(0);
    
    
    QTimer *sessionTimer = new QTimer(this);
    connect(sessionTimer, SIGNAL(timeout()), this, SLOT(sessionTimeout()));
    sessionTimer->setSingleShot(false);
    sessionTimer->setInterval(5000);
    sessionTimer->start();
    
    
    m_suppressHostUpdate = false;
}

void SynthGUI::lms_set_value(float val, LMS_control * a_ctrl )
{    
    m_suppressHostUpdate = true;
    a_ctrl->lms_set_value(int(val));
    m_suppressHostUpdate = false;     
}

void SynthGUI::setAttack(float a_value){ lms_set_value(a_value, m_adsr_amp->lms_attack);}
void SynthGUI::setDecay(float a_value){ lms_set_value(a_value, m_adsr_amp->lms_decay); }
void SynthGUI::setSustain(float a_value){lms_set_value(a_value, m_adsr_amp->lms_sustain);}
void SynthGUI::setRelease(float a_value){lms_set_value(a_value, m_adsr_amp->lms_release);}
void SynthGUI::setTimbre(float a_value){lms_set_value(a_value, m_filter->lms_cutoff_knob);}
void SynthGUI::setRes(float a_value){lms_set_value(a_value, m_filter->lms_res_knob);}
void SynthGUI::setDist(float a_value){lms_set_value(a_value, m_dist);}
void SynthGUI::setFilterAttack (float a_value){lms_set_value(a_value, m_adsr_filter->lms_attack);}
void SynthGUI::setFilterDecay  (float a_value){lms_set_value(a_value, m_adsr_filter->lms_decay);}
void SynthGUI::setFilterSustain(float a_value){lms_set_value(a_value, m_adsr_filter->lms_sustain);}
void SynthGUI::setFilterRelease(float a_value){lms_set_value(a_value, m_adsr_filter->lms_release);}
void SynthGUI::setNoiseAmp(float a_value){lms_set_value(a_value, m_noise_amp);}
void SynthGUI::setFilterEnvAmt(float a_value){lms_set_value(a_value, m_filter_env_amt);}
void SynthGUI::setDistWet(float a_value){lms_set_value(a_value, m_dist_wet);}
void SynthGUI::setOsc1Type(float a_value){lms_set_value(a_value, m_osc1->lms_osc_type_box);}
void SynthGUI::setOsc1Pitch(float a_value){lms_set_value(a_value, m_osc1->lms_pitch_knob);}
void SynthGUI::setOsc1Tune(float a_value){lms_set_value(a_value, m_osc1->lms_fine_knob);}
void SynthGUI::setOsc1Volume(float a_value){lms_set_value(a_value, m_osc1->lms_vol_knob);}
void SynthGUI::setOsc2Type(float a_value){lms_set_value(a_value, m_osc2->lms_osc_type_box);}
void SynthGUI::setOsc2Pitch(float a_value){lms_set_value(a_value, m_osc2->lms_pitch_knob);}
void SynthGUI::setOsc2Tune(float a_value){lms_set_value(a_value, m_osc2->lms_fine_knob);}
void SynthGUI::setOsc2Volume(float a_value){lms_set_value(a_value, m_osc2->lms_vol_knob);}
void SynthGUI::setMasterVolume(float a_value){lms_set_value(a_value, m_master->lms_master_volume);}
void SynthGUI::setMasterUnisonVoices(float a_value){lms_set_value(a_value, m_master->lms_master_unison_voices);}
void SynthGUI::setMasterUnisonSpread(float a_value){lms_set_value(a_value, m_master->lms_master_unison_spread);}
void SynthGUI::setMasterGlide(float a_value){lms_set_value(a_value, m_master->lms_master_glide);}
void SynthGUI::setMasterPitchbendAmt(float a_value){lms_set_value(a_value, m_master->lms_master_pitchbend_amt);}
void SynthGUI::setPitchEnvAmt(float a_value){lms_set_value(a_value, m_pitch_env->lms_amt_knob);}
void SynthGUI::setPitchEnvTime(float a_value){lms_set_value(a_value, m_pitch_env->lms_time_knob);}
void SynthGUI::setProgram(float a_value){lms_set_value(a_value, m_program);}
void SynthGUI::setLFOfreq(float a_value){lms_set_value(a_value, m_lfo->lms_freq_knob);}
void SynthGUI::setLFOtype(float a_value){lms_set_value(a_value, m_lfo->lms_type_combobox);}
void SynthGUI::setLFOamp(float a_value){lms_set_value(a_value, m_lfo_amp);}
void SynthGUI::setLFOpitch(float a_value){lms_set_value(a_value, m_lfo_pitch);}
void SynthGUI::setLFOcutoff(float a_value){lms_set_value(a_value, m_lfo_cutoff);}

void SynthGUI::lms_value_changed(int a_value, LMS_control * a_ctrl)
{    
    a_ctrl->lms_value_changed(a_value);

    if (!m_suppressHostUpdate) {
        lo_send(m_host, m_controlPath, "if", (a_ctrl->lms_port), float(a_value));
    }    
}

void SynthGUI::attackChanged(int a_value){lms_value_changed(a_value, m_adsr_amp->lms_attack);}
void SynthGUI::decayChanged(int a_value){lms_value_changed(a_value, m_adsr_amp->lms_decay);}
void SynthGUI::sustainChanged(int a_value){lms_value_changed(a_value, m_adsr_amp->lms_sustain);}
void SynthGUI::releaseChanged(int a_value){lms_value_changed(a_value, m_adsr_amp->lms_release);}
void SynthGUI::timbreChanged(int a_value){lms_value_changed(a_value, m_filter->lms_cutoff_knob);}
void SynthGUI::resChanged(int a_value){lms_value_changed(a_value, m_filter->lms_res_knob);}
void SynthGUI::distChanged(int a_value){lms_value_changed(a_value, m_dist);}
void SynthGUI::filterAttackChanged(int a_value){lms_value_changed(a_value, m_adsr_filter->lms_attack);}
void SynthGUI::filterDecayChanged(int a_value){lms_value_changed(a_value, m_adsr_filter->lms_decay);}
void SynthGUI::filterSustainChanged(int a_value){lms_value_changed(a_value, m_adsr_filter->lms_sustain);}
void SynthGUI::filterReleaseChanged(int a_value){lms_value_changed(a_value, m_adsr_filter->lms_release);}
void SynthGUI::noiseAmpChanged(int a_value){lms_value_changed(a_value, m_noise_amp);}
void SynthGUI::filterEnvAmtChanged(int a_value){lms_value_changed(a_value, m_filter_env_amt);}
void SynthGUI::distWetChanged(int a_value){lms_value_changed(a_value, m_dist_wet);}
void SynthGUI::osc1TypeChanged(int a_value){lms_value_changed(a_value, m_osc1->lms_osc_type_box);}
void SynthGUI::osc1PitchChanged(int a_value){lms_value_changed(a_value, m_osc1->lms_pitch_knob);}
void SynthGUI::osc1TuneChanged(int a_value){lms_value_changed(a_value, m_osc1->lms_fine_knob);}
void SynthGUI::osc1VolumeChanged(int a_value){lms_value_changed(a_value, m_osc1->lms_vol_knob);}
void SynthGUI::osc2TypeChanged(int a_value){lms_value_changed(a_value, m_osc2->lms_osc_type_box);}
void SynthGUI::osc2PitchChanged(int a_value){lms_value_changed(a_value, m_osc2->lms_pitch_knob);}
void SynthGUI::osc2TuneChanged(int a_value){lms_value_changed(a_value, m_osc2->lms_fine_knob);}
void SynthGUI::osc2VolumeChanged(int a_value){lms_value_changed(a_value, m_osc2->lms_vol_knob);}
void SynthGUI::masterVolumeChanged(int a_value){lms_value_changed(a_value, m_master->lms_master_volume);}
void SynthGUI::masterUnisonVoicesChanged(int a_value){lms_value_changed(a_value, m_master->lms_master_unison_voices);}
void SynthGUI::masterUnisonSpreadChanged(int a_value){lms_value_changed(a_value, m_master->lms_master_unison_spread);}
void SynthGUI::masterGlideChanged(int a_value){lms_value_changed(a_value, m_master->lms_master_glide);}
void SynthGUI::masterPitchbendAmtChanged(int a_value){lms_value_changed(a_value, m_master->lms_master_pitchbend_amt);}
void SynthGUI::pitchEnvAmtChanged(int a_value){lms_value_changed(a_value, m_pitch_env->lms_amt_knob);}
void SynthGUI::pitchEnvTimeChanged(int a_value){lms_value_changed(a_value, m_pitch_env->lms_time_knob);}
void SynthGUI::LFOfreqChanged(int a_value){lms_value_changed(a_value, m_lfo->lms_freq_knob);}
void SynthGUI::LFOtypeChanged(int a_value){lms_value_changed(a_value, m_lfo->lms_type_combobox);}
void SynthGUI::LFOampChanged(int a_value){lms_value_changed(a_value, m_lfo_amp);}
void SynthGUI::LFOpitchChanged(int a_value){lms_value_changed(a_value, m_lfo_pitch);}
void SynthGUI::LFOcutoffChanged(int a_value){lms_value_changed(a_value, m_lfo_cutoff);}
void SynthGUI::programChanged(int a_value){lms_value_changed(a_value, m_program);}
void SynthGUI::programSaved(){ m_program->programSaved(); }


void SynthGUI::v_print_port_name_to_cerr(int a_port)
{
#ifdef LMS_DEBUG_MODE_QT
    switch (a_port) {
    case LMS_ATTACK: cerr << "LMS_ATTACK"; break;
    case LMS_DECAY: cerr << "LMS_DECAY"; break;
    case LMS_SUSTAIN: cerr << "LMS_SUSTAIN"; break;
    case LMS_RELEASE: cerr << "LMS_RELEASE"; break;
    case LMS_TIMBRE: cerr << "LMS_TIMBRE"; break;
    case LMS_RES: cerr << "LMS_RES"; break;        
    case LMS_DIST: cerr << "LMS_DIST"; break;
    case LMS_FILTER_ATTACK: cerr << "LMS_FILTER_ATTACK"; break;
    case LMS_FILTER_DECAY: cerr << "LMS_FILTER_DECAY"; break;
    case LMS_FILTER_SUSTAIN: cerr << "LMS_FILTER_SUSTAIN"; break;
    case LMS_FILTER_RELEASE: cerr << "LMS_FILTER_RELEASE"; break;
    case LMS_NOISE_AMP: cerr << "LMS_NOISE_AMP"; break;    
    case LMS_DIST_WET: cerr << "LMS_DIST_WET"; break;            
    case LMS_FILTER_ENV_AMT: cerr << "LMS_FILTER_ENV_AMT"; break;    
    case LMS_OSC1_TYPE: cerr << "LMS_OSC1_TYPE"; break;            
    case LMS_OSC1_PITCH: cerr << "LMS_OSC1_PITCH"; break;    
    case LMS_OSC1_TUNE: cerr << "LMS_OSC1_TUNE"; break;    
    case LMS_OSC1_VOLUME: cerr << "LMS_OSC1_VOLUME"; break;        
    case LMS_OSC2_TYPE: cerr << "LMS_OSC2_TYPE"; break;            
    case LMS_OSC2_PITCH: cerr << "LMS_OSC2_PITCH"; break;    
    case LMS_OSC2_TUNE: cerr << "LMS_OSC2_TUNE";  break;    
    case LMS_OSC2_VOLUME: cerr << "LMS_OSC2_VOLUME"; break;        
    case LMS_MASTER_VOLUME: cerr << "LMS_MASTER_VOLUME"; break;
    case LMS_MASTER_UNISON_VOICES: cerr << "LMS_MASTER_UNISON_VOICES"; break;
    case LMS_MASTER_UNISON_SPREAD: cerr << "LMS_MASTER_UNISON_SPREAD"; break;
    case LMS_MASTER_GLIDE: cerr << "LMS_MASTER_GLIDE"; break;
    case LMS_MASTER_PITCHBEND_AMT: cerr << "LMS_MASTER_PITCHBEND_AMT"; break;
    case LMS_PITCH_ENV_AMT: cerr << "LMS_PITCH_ENV_AMT "; break;
    case LMS_PITCH_ENV_TIME: cerr << "LMS_PITCH_ENV_TIME ";  break;        
    case LMS_PROGRAM_CHANGE: cerr << "LMS_PROGRAM_CHANGE "; break;
    default: cerr << "Warning: received request to set nonexistent port " << a_port ; break;
    }
#endif
}

void SynthGUI::v_set_control(int a_port, float a_value)
{

#ifdef LMS_DEBUG_MODE_QT    
    cerr << "v_set_control called.  ";  
    v_print_port_name_to_cerr(a_port);
    cerr << "  value: " << a_value << endl;
#endif
        
    switch (a_port) {
        case LMS_ATTACK: setAttack(a_value); break;
        case LMS_DECAY: setDecay(a_value); break;
        case LMS_SUSTAIN: setSustain(a_value); break;
        case LMS_RELEASE: setRelease(a_value); break;
        case LMS_TIMBRE: setTimbre(a_value); break;
        case LMS_RES: setRes(a_value); break;
        case LMS_DIST: setDist(a_value); break;
        case LMS_FILTER_ATTACK: setFilterAttack(a_value); break;
        case LMS_FILTER_DECAY: setFilterDecay(a_value); break;
        case LMS_FILTER_SUSTAIN: setFilterSustain(a_value); break;
        case LMS_FILTER_RELEASE: setFilterRelease(a_value); break;
        case LMS_NOISE_AMP: setNoiseAmp(a_value); break;    
        case LMS_DIST_WET: setDistWet(a_value); break;
        case LMS_FILTER_ENV_AMT: setFilterEnvAmt(a_value); break;    
        case LMS_OSC1_TYPE: setOsc1Type(a_value); break;            
        case LMS_OSC1_PITCH: setOsc1Pitch(a_value);  break;    
        case LMS_OSC1_TUNE: setOsc1Tune(a_value); break;    
        case LMS_OSC1_VOLUME: setOsc1Volume(a_value); break;        
        case LMS_OSC2_TYPE: setOsc2Type(a_value); break;            
        case LMS_OSC2_PITCH: setOsc2Pitch(a_value); break;    
        case LMS_OSC2_TUNE: setOsc2Tune(a_value); break;    
        case LMS_OSC2_VOLUME: setOsc2Volume(a_value); break;        
        case LMS_MASTER_VOLUME: setMasterVolume(a_value); break;    
        case LMS_MASTER_UNISON_VOICES: setMasterUnisonVoices(a_value); break;
        case LMS_MASTER_UNISON_SPREAD: setMasterUnisonSpread(a_value); break;
        case LMS_MASTER_GLIDE: setMasterGlide(a_value); break;
        case LMS_MASTER_PITCHBEND_AMT: setMasterPitchbendAmt(a_value); break;
        case LMS_PITCH_ENV_AMT: setPitchEnvAmt(a_value); break;
        case LMS_PITCH_ENV_TIME: setPitchEnvTime(a_value); break;            
        case LMS_PROGRAM_CHANGE: setProgram(a_value); break;            
        case LMS_LFO_FREQ: setLFOfreq(a_value); break;            
        case LMS_LFO_TYPE:  setLFOtype(a_value);  break;            
        case LMS_LFO_AMP: setLFOamp(a_value); break;            
        case LMS_LFO_PITCH: setLFOpitch(a_value); break;            
        case LMS_LFO_FILTER: setLFOcutoff(a_value); break;
    }
    
}

void SynthGUI::v_control_changed(int a_port, int a_value, bool a_suppress_host_update)
{
    
#ifdef LMS_DEBUG_MODE_QT    
    cerr << "v_control_changed called.  ";  
    v_print_port_name_to_cerr(a_port);
    cerr << "  value: " << a_value << endl;
#endif
    
    if(a_suppress_host_update)
        m_suppressHostUpdate = true;      
    
    switch (a_port) {
    case LMS_ATTACK: attackChanged(a_value); break;
    case LMS_DECAY: decayChanged(a_value); break;
    case LMS_SUSTAIN: sustainChanged(a_value); break;
    case LMS_RELEASE: releaseChanged(a_value); break;
    case LMS_TIMBRE: timbreChanged(a_value); break;
    case LMS_RES: resChanged(a_value); break;        
    case LMS_DIST: distChanged(a_value); break;
    case LMS_FILTER_ATTACK: filterAttackChanged(a_value); break;
    case LMS_FILTER_DECAY: filterDecayChanged(a_value); break;
    case LMS_FILTER_SUSTAIN: filterSustainChanged(a_value); break;
    case LMS_FILTER_RELEASE: filterReleaseChanged(a_value); break;
    case LMS_NOISE_AMP: noiseAmpChanged(a_value); break;    
    case LMS_DIST_WET: distWetChanged(a_value); break;
    case LMS_FILTER_ENV_AMT: filterEnvAmtChanged(a_value); break;    
    case LMS_OSC1_TYPE: osc1TypeChanged(a_value);  break;            
    case LMS_OSC1_PITCH:  osc1PitchChanged(a_value);  break;    
    case LMS_OSC1_TUNE: osc1TuneChanged(a_value); break;    
    case LMS_OSC1_VOLUME: osc1VolumeChanged(a_value); break;
    case LMS_OSC2_TYPE: osc2TypeChanged(a_value); break;            
    case LMS_OSC2_PITCH: osc2PitchChanged(a_value); break;    
    case LMS_OSC2_TUNE: osc2TuneChanged(a_value); break;    
    case LMS_OSC2_VOLUME: osc2VolumeChanged(a_value); break;
    case LMS_MASTER_VOLUME: masterVolumeChanged(a_value); break;
    case LMS_MASTER_UNISON_VOICES: masterUnisonVoicesChanged(a_value); break;
    case LMS_MASTER_UNISON_SPREAD: masterUnisonSpreadChanged(a_value); break;
    case LMS_MASTER_GLIDE: masterGlideChanged(a_value); break;
    case LMS_MASTER_PITCHBEND_AMT: masterPitchbendAmtChanged(a_value); break;
    case LMS_PITCH_ENV_AMT: pitchEnvAmtChanged(a_value); break;
    case LMS_PITCH_ENV_TIME: pitchEnvTimeChanged(a_value); break;
    case LMS_LFO_FREQ: LFOfreqChanged(a_value); break;
    case LMS_LFO_TYPE: LFOtypeChanged(a_value); break;
    case LMS_LFO_AMP: LFOampChanged(a_value); break;
    case LMS_LFO_PITCH: LFOpitchChanged(a_value); break;
    case LMS_LFO_FILTER: LFOcutoffChanged(a_value); break;
    case LMS_PROGRAM_CHANGE: programChanged(a_value);  break;
    default:
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Warning: received request to set nonexistent port " << a_port << endl;
#endif
        break;
    }
    
    if(a_suppress_host_update)
        m_suppressHostUpdate = false;
    
}

/*TODO:  For the forseeable future, this will only be used for getting the values to write back to 
 the presets.tsv file;  It should probably return a string that can be re-interpreted into other values for
 complex controls that could have multiple ints, or string values, etc...*/
int SynthGUI::i_get_control(int a_port)
{
        /*Add the controls you created to the control handler*/
    
    switch (a_port) {
    case LMS_ATTACK: return  m_adsr_amp->lms_attack->lms_get_value();
    case LMS_DECAY:  return m_adsr_amp->lms_decay->lms_get_value();
    case LMS_SUSTAIN: return m_adsr_amp->lms_sustain->lms_get_value();
    case LMS_RELEASE: return m_adsr_amp->lms_release->lms_get_value();
    case LMS_TIMBRE: return  m_filter->lms_cutoff_knob->lms_get_value();
    case LMS_RES: return m_filter->lms_res_knob->lms_get_value();        
    case LMS_DIST: return m_dist->lms_get_value();
    case LMS_FILTER_ATTACK: return m_adsr_filter->lms_attack->lms_get_value();
    case LMS_FILTER_DECAY: return m_adsr_filter->lms_decay->lms_get_value();
    case LMS_FILTER_SUSTAIN: return m_adsr_filter->lms_sustain->lms_get_value();
    case LMS_FILTER_RELEASE: return m_adsr_filter->lms_release->lms_get_value();
    case LMS_NOISE_AMP: return m_noise_amp->lms_get_value();
    case LMS_DIST_WET: return m_dist_wet->lms_get_value();
    case LMS_FILTER_ENV_AMT: return m_filter_env_amt->lms_get_value();
    case LMS_OSC1_TYPE: return m_osc1->lms_osc_type_box->lms_get_value();
    case LMS_OSC1_PITCH: return m_osc1->lms_pitch_knob->lms_get_value();
    case LMS_OSC1_TUNE: return  m_osc1->lms_fine_knob->lms_get_value();
    case LMS_OSC1_VOLUME: return m_osc1->lms_vol_knob->lms_get_value();
    case LMS_OSC2_TYPE:  return m_osc2->lms_osc_type_box->lms_get_value();
    case LMS_OSC2_PITCH: return m_osc2->lms_pitch_knob->lms_get_value();
    case LMS_OSC2_TUNE: return m_osc2->lms_fine_knob->lms_get_value();
    case LMS_OSC2_VOLUME: return m_osc2->lms_vol_knob->lms_get_value();
    case LMS_MASTER_VOLUME: return m_master->lms_master_volume->lms_get_value();
    case LMS_MASTER_UNISON_VOICES: return m_master->lms_master_unison_voices->lms_get_value();
    case LMS_MASTER_UNISON_SPREAD: return m_master->lms_master_unison_spread->lms_get_value();
    case LMS_MASTER_GLIDE: return m_master->lms_master_glide->lms_get_value();
    case LMS_MASTER_PITCHBEND_AMT: return m_master->lms_master_pitchbend_amt->lms_get_value();
    case LMS_PITCH_ENV_AMT: return m_pitch_env->lms_amt_knob->lms_get_value();
    case LMS_PITCH_ENV_TIME: return m_pitch_env->lms_time_knob->lms_get_value();
    case LMS_LFO_FREQ: return m_lfo->lms_freq_knob->lms_get_value();
    case LMS_LFO_TYPE: return m_lfo->lms_type_combobox->lms_get_value();
    case LMS_LFO_AMP: return m_lfo_amp->lms_get_value();
    case LMS_LFO_PITCH: return m_lfo_pitch->lms_get_value();
    case LMS_LFO_FILTER: return m_lfo_cutoff->lms_get_value();
    //case LMS_PROGRAM_CHANGE:
        //return m_program->currentIndex();
    default:
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Warning: received request to get nonexistent port " << a_port << endl;
#endif
        return 0;
        break;
    }    
}

void SynthGUI::test_press()
{
    unsigned char noteon[4] = { 0x00, 0x90, 0x2A, 0x66 };
    lo_send(m_host, m_midiPath, "m", noteon);
}

void SynthGUI::oscRecv()
{
    if (osc_server) {
	lo_server_recv_noblock(osc_server, 1);
    }
}

void SynthGUI::sessionTimeout()
{
    cerr << instance_name << " " << project_path << " sessionTimeout called...\n";
    
    if(lms_session_manager::is_saving(project_path, instance_name))
    {
        cerr << "Is saving...\n";
        //Currently works by saving the entire preset file
        m_program->write_presets_to_file(project_path + QString("/") + instance_name + LMS_SESSION_INSTRUMENT_FILE);
    }
    
    if(lms_session_manager::is_quitting(project_path, instance_name))
    {
        
    }        
}

void SynthGUI::test_release()
{
    unsigned char noteoff[4] = { 0x00, 0x90, 0x2A, 0x00 };

    lo_send(m_host, m_midiPath, "m", noteoff);
}

void SynthGUI::aboutToQuit()
{
    if (!m_hostRequestedQuit) lo_send(m_host, m_exitingPath, "");
}

SynthGUI::~SynthGUI()
{
    lo_address_free(m_host);
}


void osc_error(int num, const char *msg, const char *path)
{
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Error: liblo server error " << num
	 << " in path \"" << (path ? path : "(null)")
	 << "\": " << msg << endl;
#endif
}

int debug_handler(const char *path, const char *types, lo_arg **argv,
	      int argc, void *data, void *user_data)
{
    int i;
#ifdef LMS_DEBUG_MODE_QT
      cerr << "Warning: unhandled OSC message in GUI:" << endl;
#endif
    

    for (i = 0; i < argc; ++i) {
#ifdef LMS_DEBUG_MODE_QT
	cerr << "arg " << i << ": type '" << types[i] << "': ";
#endif
        lo_arg_pp((lo_type)types[i], argv[i]);
#ifdef LMS_DEBUG_MODE_QT
	cerr << endl;
#endif
    }
#ifdef LMS_DEBUG_MODE_QT
    cerr << "(path is <" << path << ">)" << endl;
#endif
    return 1;
}

int program_handler(const char *path, const char *types, lo_arg **argv,
	       int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    
    //int bank = 0;
    int program = 0;

    /*
    if (argc < 2) {
        //GDB_MESSAGE(GDB_OSC, " error: too few arguments to osc_program_handler\n");
        return 1;
    }

    
    bank = argv[0]->i;
    program = argv[1]->i;

    if (bank || program < 0 || program >= 128) {        
        return 0;
    }
    */
#ifdef LMS_DEBUG_MODE_QT
    cerr << "Bank:  " << bank << ", Program:  " << program << endl;
#endif
    gui->setProgram(program);

    return 0;
}

int configure_handler(const char *path, const char *types, lo_arg **argv,
		  int argc, void *data, void *user_data)
{
    return 0;
}

int rate_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    return 0; /* ignore it */
}

int show_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    while (!gui->ready()) sleep(1);
    if (gui->isVisible()) gui->raise();
    else gui->show();
    return 0;
}

int hide_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    gui->hide();
    return 0;
}

int quit_handler(const char *path, const char *types, lo_arg **argv,
	     int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);
    gui->setHostRequestedQuit(true);
    qApp->quit();
    return 0;
}

int control_handler(const char *path, const char *types, lo_arg **argv,
		int argc, void *data, void *user_data)
{
    SynthGUI *gui = static_cast<SynthGUI *>(user_data);

    if (argc < 2) {
        
#ifdef LMS_DEBUG_MODE_QT
	cerr << "Error: too few arguments to control_handler" << endl;
#endif
	return 1;
    }

    const int port = argv[0]->i;
    const float value = argv[1]->f;

#ifdef LMS_DEBUG_MODE_QT
    cerr << "control_handler called.  port:  " << port << " , value " << value << endl;
#endif

    gui->v_set_control(port, value);  
     
    gui->v_control_changed(port, value, true);

    return 0;
}

int main(int argc, char **argv)
{

    cerr << "Qt GUI main() called..." << endl;

    
    QApplication application(argc, argv);

    if (application.argc() < 5)
    {

	cerr << "usage: "
	     << application.argv()[0] 
	     << " <osc url>"
	     << " <plugin dllname>"
	     << " <plugin label>"
	     << " <user-friendly id>"
	     << endl;

	return 2;
    }

#ifdef Q_WS_X11
    XSetErrorHandler(handle_x11_error);
#endif

    char *url = application.argv()[1];

    char *host = lo_url_get_hostname(url);
    char *port = lo_url_get_port(url);
    char *path = lo_url_get_path(url);

    SynthGUI gui(host, port,
		 QByteArray(path) + "/control",
		 QByteArray(path) + "/midi",
		 QByteArray(path) + "/program",
		 QByteArray(path) + "/exiting",
		 0);
 
    QByteArray myControlPath = QByteArray(path) + "/control";
    QByteArray myProgramPath = QByteArray(path) + "/program";
    QByteArray myConfigurePath = QByteArray(path) + "/configure";
    QByteArray myRatePath = QByteArray(path) + "/sample-rate";
    QByteArray myShowPath = QByteArray(path) + "/show";
    QByteArray myHidePath = QByteArray(path) + "/hide";
    QByteArray myQuitPath = QByteArray(path) + "/quit";

    cerr << "Adding lo server methods" << endl;

    osc_server = lo_server_new(NULL, osc_error);
    lo_server_add_method(osc_server, myControlPath, "if", control_handler, &gui);
    lo_server_add_method(osc_server, myProgramPath, "ii", program_handler, &gui);
    lo_server_add_method(osc_server, myConfigurePath, "ss", configure_handler, &gui);
    lo_server_add_method(osc_server, myRatePath, "i", rate_handler, &gui);
    lo_server_add_method(osc_server, myShowPath, "", show_handler, &gui);
    lo_server_add_method(osc_server, myHidePath, "", hide_handler, &gui);
    lo_server_add_method(osc_server, myQuitPath, "", quit_handler, &gui);
    lo_server_add_method(osc_server, NULL, NULL, debug_handler, &gui);

    lo_address hostaddr = lo_address_new(host, port);
    lo_send(hostaddr,
	    QByteArray(path) + "/update",
	    "s",
	    (QByteArray(lo_server_get_url(osc_server))+QByteArray(path+1)).data());

    QObject::connect(&application, SIGNAL(aboutToQuit()), &gui, SLOT(aboutToQuit()));

    gui.setReady(true);
    gui.is_session = FALSE;
    
    if(argc >= 7)
    {
        gui.project_path = QString(application.argv()[5]);
        gui.instance_name = QString(application.argv()[6]);
        
        gui.is_session = TRUE;
        
        cerr << gui.project_path << "\n" << gui.instance_name << "\n";
    }
    else
    {
        cerr << QString("argc==") << QString::number(argc) << QString("\n");
    }
    
    cerr << "Starting GUI now..." << endl;
    
    return application.exec();
}

